lib/eventum/class.report.php, lib/eventum/class.time_tracking.php
start/end date in datetime not timestamp format for Time_Tracking::getSummaryByUser
otherwise SQL error:
Warning (Code 1292): Incorrect datetime value: '1422223200' for column 'ttr_created_date' at row 1
=> start/end date in datetime not timestamp format 

lib/eventum/class.email_account.php, lib/eventum/class.issue.php, lib/eventum/class.support.php
Project ID will be taken from issue ID instead. Closing comments are not displayed since emails are hidden if there is no email account.
This behavior is better then previous runtime error but still not perfect. We could either:
a) always add a dummy email account when creating a project.
b) always display the email section, just hide the "send email" button if there is no account setup.
=> Fix error closing issue with no email accounts.

lib/eventum/class.note.php, lib/eventum/class.support.php
MySQL's auto type conversion was causing incorrect threading. Now we are validating input to prevent this.
=> Fix bug with incorrect message threading.

templates/index.tpl.html
change login texts so login could mean email or ldap user id.
changed only texts, ideally should rename `email` form data as well.
also did not want to query what is current auth backend, as that would make extra round-trip to ldap server (with current code), and leaking auth system info maybe is not that good idea.
=> login texts change

upgrade/patches/30_migrate_tz.php
the underlying problem is that if user timezone is `EET` instead `Europe/Tallinn`, their timetracking entries get off by one hour when DST is active.
=> convert user preference timezone in abbreviation to timezone

lib/eventum/class.report.php
make "Separate No time spent" filter work when "Show Times spent on issue" is not checked in Weekly Report
=> fix "Separate No time spent" filter in WeeklyReport

htdocs/css/page.css, templates/bulk_update.tpl.html
Global:
* don't create bigger area, when clicking on Choose Assignees, make it 27px, let the dropdown act like dropdown not new 240px height div
* style changes: separate default chosen dropdowns and bulk update dropdown. nicer dropdown shadows 
Bulk update:
* when bulk update, add dummy/empty option, so first assignee will not be selected automatically when clicking on dropdown
* bulk update vs chosen conflict - dropdown makes page longer and chosen selects the item under mouse, lets open assignee list to the top, not below
* minor style changes: cast shadow to top, not to bottom, as dropdown opens to top
=> Chosen (Assignee selection dropdown) fixes

.gitignore, composer.json, docs/examples/config/cas.php, htdocs/index.php, htdocs/login.php, lib/eventum/auth/class.auth_backend_interface.php, lib/eventum/auth/class.cas_auth_backend.php, lib/eventum/auth/class.ldap_auth_backend.php, lib/eventum/auth/class.mysql_auth_backend.php, lib/eventum/autoload.php, lib/eventum/class.auth.php, lib/eventum/class.session.php, templates/index.tpl.html
This adds support for Central Authentication Service (CAS) in Eventum. The backend totally replaces the built in auth and does not allow fallback. If configured, Eventum will create new users.
Changes to auth interface are:
* Addition of getExternalLoginURL() method. If set no login form will be displayed. Instead the user
will be redirect to an external URL to authenticate.
* Addition of checkAuthentication() method. This is called before the normal Eventum authentication
process.
* Addition of logout() method. This is called after the Eventum logout process is completed.
I'm not 100% sure that getExternalLoginURL() and checkAuthentication() is the cleanest way but I haven't thought of a better way.
Please let me know any feedback you have on this or if you have any better ideas on how …
=> CAS Auth Backend

docs/UPGRADE.md, lib/eventum/class.email_account.php
Fix POP3 email download bug (Issue #66) where $mailbox was null, but a null string in the pre 3.02 database caused the email account ID to be zero.
Also changed UPGRADE.md to reflect location change of cron jobs.
=> Fix POP3 email download bug (Issue #66)

lib/eventum/class.custom_field.php, lib/eventum/class.display_column.php, lib/eventum/class.group.php, lib/eventum/class.pager.php, lib/eventum/class.search_profile.php
Added static keyword to methods causing PHP Strict notifications. 
Changed call to remove deprecated use of /e in preg_replace in Pager::getTotalRows.  It doesn't appear Eventum needed /e in the first place as we did not need to eval the replacement values.
=> Static & Deprecated calls

bin/release.sh, composer.json, htdocs/manage/private_key.php, htdocs/setup/index.php, lib/eventum/class.auth.php, lib/eventum/class.misc.php, localization/eventum.pot, templates/manage/manage.tpl.html, templates/manage/private_key.tpl.html, tests/RandomLibTest.php
use [randomlib](https://github.com/ircmaxell/RandomLib) for initial private key generation. i wonder how many bytes is enough?
also adds new admin panel to regenerate private key.
admin probably needs [CSRF](https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet) protection.
as for private key, maybe use `sha1` instead of `md5`? or just store it as raw bytes?
=> use randomlib for private key

composer.json, htdocs/preferences.php, lib/eventum/auth/AuthPassword.php, lib/eventum/auth/class.mysql_auth_backend.php, lib/eventum/class.auth.php, lib/eventum/class.user.php, templates/preferences.tpl.html, tests/PasswordAuthTest.php, upgrade/patches/34_password_hash.sql
uses [password_hash](https://wiki.php.net/rfc/password_hash) family functions by default.
[compatibility library](https://github.com/ircmaxell/password_compat) for older php versions is included
new passwords are set using new algorithm, existing hashes will be verified using old methods.
auto migration of hash on successful login and hash upgrade can be added in later releases.
also added old password prompt when changing password and trivial check such as new and old passwords differ (auth backend said `false` anyway for such password change)
also includes sql patch to clear password for accounts where empty password was stored for whatever reason.
=> refactor password handling

htdocs/csv.php, htdocs/get_attachment.php, lib/eventum/class.attachment.php, upgrade/patches/36_iaf_filesize.sql
fixes to file attachments corrupted when mbstring overloading is enabled. [LP#1494732](https://bugs.launchpad.net/eventum/+bug/1494732)
=> File Attachments Corrupted when mbstring Overloading is Enabled

composer.json, htdocs/manage/general.php, htdocs/manage/monitor.php, htdocs/manage/scm.php, htdocs/rss.php, htdocs/setup/index.php, lib/eventum/class.db_helper.php, lib/eventum/class.mail_helper.php, lib/eventum/class.scm.php, lib/eventum/class.setup.php, lib/eventum/workflow/class.abstract_workflow_backend.php, tests/ConfigTest.php, tests/IssueLockTest.php, tests/bootstrap.php, upgrade/patches/33_set_required_fields.php, upgrade/patches/38_config.php
besides dual usage (via object and array),
the Setup::save takes only keys you want to modify, no need for Setup::load
and if you modify the retrieved setup, the in-memory version is modified too.
using zf2 lts version (2.4)
=> use zf2 config for setup config

composer.json, init.php, lib/eventum/class.template_helper.php, templates/base.tpl.html
adds add [DebugBar](http://phpdebugbar.com/) debug bar.
currently exposes:
the toolbar is enabled if:
- `DebugBar\StandardDebugBar` class can be loaded (`composer install --dev`)
- user level is administrator
the protection is made because debugbar can (and will) reveal sensitive information and should not be used in production nodes in regular basis.
=> add DebugBar debug bar

htdocs/close.php, htdocs/custom_fields.php, htdocs/js/main.js, htdocs/js/page.js, htdocs/manage/custom_fields.php, htdocs/update.php, lib/eventum/class.custom_field.php, lib/eventum/class.history.php, lib/eventum/class.issue.php, lib/eventum/class.issue_field.php, lib/eventum/class.notification.php, templates/custom_fields.tpl.html, templates/edit_custom_fields.tpl.html, templates/history.tpl.html, templates/notifications/updated.tpl.text, templates/update_form.tpl.html, upgrade/patches/40_history_role.php
Custom fields are now included on the update issue page. During the implementation I fixed a bunch of little custom field related bugs.
* Include custom fields in update issue page.
* Fixed bug updating custom field definitions.
* Display admin only custom fields in 'internal' color.
* Fix bug unchecking checkbox custom fields.
* Include custom field changes in issue updated email.
* Fix data leakage problem with admin only custom fields by restricting history entries to correct role.
* Added minimum role to each history entry. If no role is specified it will default to role from history type.
Custom fields are displayed in a separate box, if we overhaul the UI we might want to include them with the rest of the issue details.
=> Update custom fields from update issue page

bin/download_emails.php, htdocs/manage/check_email_settings.php, templates/get_emails.tpl.html
@glensc I didn't see that you also fixed this until after.. this pull also fixes the notice.  I used Misc::ifSet that you referenced in the notes.
I also added a new line to the error text when imap_open is missing:
"It is installed by default on some systems but must also be enabled. See INSTALL.md"
The error previously only referenced checking the PHP docs.. the PHP site is silent on enabling.
INSTALL.md isn't there any more (so i didn't edit) - we need a note that imap needs to be installed **and** enabled.  `php5enmod -s ALL imap` should do it on most linux machines.  Works on Ubuntu.
=> Issue 91 notice and IMAP missing error change

htdocs/css/main.css, htdocs/manage/check_email_settings.php, templates/base.tpl.html, templates/base_full.tpl.html, templates/get_emails_ajax.tpl.html, templates/manage/email_accounts.tpl.html
Display of result on page instead of popup.  Popup was not a form in this case.
Also changed base.tpl to move full_width_messages div outside block so it appears on every page.
This is in preparation for later enhancing other pages to use this div
for AJAX response messages. base_full.tpl was modified and the messages block was
removed so as not to override base.tpl (looked duplicative anyway)
I am proposing this as a template for making similar changes to other pages which use pop-ups only for results.  Any clean-up/enhancements (particularly css) are welcome.
=> Ajax email test

.htaccess
this will at least redirect to htdocs subdir for poortly setup
installations.
originally i intended to add there `Require all denied` and `Require all granted` when directory is `htdocs`, but wasn't able to accomplish that without the same `.htaccess` matching in `htdocs/` dir.
so just kept rewrite rules. which also originally were conditional `<IfModule mod_rewrite.c>`, but removed condition, so that if you two of these:
- expose directory outside htdocs to web
- don't have mod_rewrite enabled either 
you will get 500 error about misconfiguration and it's good indication that you should really check your installation and read some docs.
making the web safer place!
=> add .htaccess to project root

composer.json, htdocs/ajax/upload.php, htdocs/file_upload.php, htdocs/offline.php, htdocs/preferences.php, htdocs/scm_ping.php, init.php, lib/eventum/Logger.php, lib/eventum/class.auth.php, lib/eventum/class.db_helper.php, lib/eventum/class.mail_helper.php, lib/eventum/class.mail_queue.php, lib/eventum/class.mime_helper.php, lib/eventum/class.setup.php, lib/eventum/class.support.php, lib/eventum/class.user.php, lib/eventum/db/DbPear.php, lib/eventum/rpc/RemoteApi.php, lib/eventum/search/class.sphinx_fulltext_search.php, tests/LoggerTest.php, tests/bootstrap.php
this adds framework to have common logging in code.
as we're in legacy-codebase situation, best fit was to use [Monolog\Registry](https://github.com/Seldaek/monolog/blob/1.17.2/doc/03-utilities.md)
overview is simple, call this in `init.php`:
```php
Logger::initialize();
```
and when want to log:
```php
Logger::db()->error('Sent to $db Logger instance');
Logger::app()->error('Sent to $app Logger instance');
```
Levels below `WARNING` are not logged anywhere, but it's pretty easy to setup something to do so. it's in single location (`Logger` class).
sub tasks:
=> add logging framework based on monolog

config/config.dist.php, htdocs/css/page.css, htdocs/js/main.js, htdocs/js/page.js, templates/select_project.tpl.html
Users can now one click anywhere on the project name cell to choose a project and submit.
Project cookie will last 30 days by default.
Project cookie will "remember" by default.
The only question I have is if we want to try to change the project lifetime that users already have set in their config.php. I don't think we have any mechanism to change that file. I suppose we could move it into the setup file though. Thoughts?
=> Improve select project page and increase project cookie lifespan.

htdocs/js/main.js, htdocs/manage/general.php, lib/eventum/class.prefs.php, lib/eventum/class.setup.php, templates/base.tpl.html, templates/manage/general.tpl.html, templates/preferences.tpl.html, upgrade/patches/44_usr_relative_dates.php
Our internal users do not like time ago so I added a setup option to disable it. It is enabled by default.
=> Added setup option to disable timeago

htdocs/css/page.css
Prevent long lines make width very long, wrap them to the next line. Based on CSS provided by Risto Risti.
Inside issue view:
Note view:
=> fix wrapping the long lines

lib/eventum/class.routing.php, lib/eventum/class.support.php
reuse existing Routing::route to route mails from support::getEmailInfo
some methods made private as they are no longer used elsewhere.
i have not tested the code yet, it's hard to test this in dev environment, but i compared the methods and they seem to do similar thing
there was some confusion with `ema_leave_copy` handling. i think it got in broken in initial commit dc0bf7185 (Eventum 2.2), which is probably now fixed with 137bd2b943a
=> reuse existing Routing::route to route mails from support::getEmailInfo

lib/eventum/class.workflow.php, lib/eventum/workflow/class.abstract_workflow_backend.php, src/Crypto/CryptoUpgradeManager.php
enhancement to original crypto implementation #134
this allows workflow to encrypt specific keys in config
that eventum core has no idea about that need to be encrypted
NOTE: the project id for workflow is hardcoded to `1`, as this workflow is not project specific. and i don't think there are many workflow users out there who have more than one workflow class defined.
ideally workflow mechanism should be reworked to allow the project-less workflow naturally
=> add workflow methods for crypt upgrade/downgrade

upgrade/patches/48_maq_message_id.php
Add Message-Id column to mail queue table
idea is to implement 5d043aaccbee438091081232125684fe3a6e0da5 better, using Message-Id
see discussion in Launchpad
https://bugs.launchpad.net/pld-linux/+bug/1195856
This depends on #139, so it should be merged first
=> Add Message-Id column to mail queue table

htdocs/setup/index.php, lib/eventum/class.db_helper.php
this is part of deprecation process in 3.1 series
pdo drivers are the recommended drivers in modern php
the pdo driver as been around since [3.0.4](https://github.com/eventum/eventum/tree/v3.0.4/lib/eventum/db)
=> use pdo_mysql as default mysql driver

ChangeLog.md, lib/eventum/class.mail_helper.php, tests/ForwardedRoutingTest.php, tests/data/thunderbird-forwarded.txt
Time to time you take existing Eventum Note or Email and forward it to `support@` address.
Your intention is to create new issue from it, but Thunderbird includes `In-Reply-To` header like it's `reply`, but it's really `forward`. It also includes `X-Forwarded-Message-Id` header. use that to detect it's forward not reply.
=> Do not associate forwarded emails to original issue

ChangeLog.md, lib/eventum/class.issue.php, src/Model/Entity/BaseModel.php, src/Model/Entity/IssueAssociation.php, src/Model/Repository/IssueAssociationRepository.php, tests/IssueAssociationTest.php
there's some bug that sometimes adding issue association shows up only one side of issue pair, and each time trying to fix that adds the associated issue id to the other issue that already had one, and the first issue stays without association.
decided to rewrite that portion of code and add unit tests to resolve this issue.
the change involves that into `issue_association` table only one row of association is inserted instead of current two, thus simplifying all logic.
=> rewrite issue association code

lib/eventum/class.time_tracking.php
In "Manage Projects", "Manage Time Tracking Categories".
When any "Time Tracking Categories"  doesn't exists in the Project, for example a new project is created, error appear on click "Manage Time Tracking Categories".
=> Error : "Manage Time Tracking Categories"

ChangeLog.md, docs/examples/templates/customer/customer_info.tpl.html, docs/examples/templates/customer/report_form_fields.tpl.html, lib/eventum/class.template_helper.php, templates/base_full.tpl.html
All variables set by default are now part of the $core variable.
This might impact 3rd party templates, but the fix is a simple search and replace.
=> Remove duplicate variables from templates

ChangeLog.md, lib/eventum/class.support.php
This is a redo of #190 to avoid the merge mess.
Allowed replies to use non-subject based "in-reply-to" for message-id matching (when subject based routing is enabled).
It does this by allowing the existing else clause and references behaviour for non-subject based routing to also occur when the subject line does not contain [#IssueID].
@glensc The change adds to the if so that when subject based routing is enabled it still processes the else block if there is no [#IssueID] in the subject line.  
```
and (preg_match("/\[#(\d+)\]( Note| BLOCKED)*/", $subject, $matches)))
```
This allows those who enable subject based routing to also follow the "in-reply-to" message id back to the original issue.  This code was already in place if subject based routing was not enabled.
Changelog also …
=> Use "in-reply-to" mail header to find Issue ID

bin/irc-bot.php, bin/process_all_emails.php, build.xml, composer.json, lib/eventum/class.lock.php, lib/eventum/irc/Eventum_Bot.php, src/Command/Command.php, src/Command/DownloadEmailsCommand.php, src/ConcurrentLock.php
i've planning to do this long time ago. the locking can be made really accurate in scope of one machine by using [flock](http://php.net/flock).
this should also solve user errors, who are unable to remove locks: #202
this removes writing pid files and `--fix-lock` arguments as it is no longer necessary.
the current code uses [malkusch/lock](https://github.com/malkusch/lock):
```php
$mutex->synchronized(function () use ($bankAccount, $amount) {
$balance = $bankAccount->getBalance();
$balance -= $amount;
if ($balance < 0) {
throw new \DomainException("You have no credit.");
}
$bankAccount->setBalance($balance);
});
```
the lock is automatically released when the code block exits.
the downside is that the locks are waited forever until the locked process still runs (lock is removed if …
=> rewrite locking code to use flock

ChangeLog.md, lib/eventum/class.access.php
make public attachments visible for Reporters, fixes #214
the [Access::canViewAttachedFiles()](https://github.com/eventum/eventum/blame/v3.1.4/lib/eventum/class.access.php#L117-L131) was added in 3836501 and it checked for `Customer` Role. That change was released first as 2.4.0pre1
the change also added `{if $issue_access.files}` condition in [view.tpl](https://github.com/eventum/eventum/commit/38365011f33a19dae2d2816f9fe2b04af882f008#diff-0b7308e0fb8a837778d273399e99a1ee) which was not present before, i.e the `{include file="attachments.tpl.html"}` was loaded unconditionally
=> make public attachments visible for Reporters fixes #214

ChangeLog.md, lib/eventum/class.issue.php, lib/eventum/class.workflow.php, lib/eventum/workflow/class.abstract_workflow_backend.php
This can be used to map values for fields between projects or do other custom changes.
=> Workflow change project

ChangeLog.md, composer.json, lib/eventum/class.mail_helper.php, lib/eventum/class.mail_queue.php, lib/eventum/class.mime_helper.php, lib/eventum/class.notification.php, lib/eventum/class.reminder_action.php, lib/eventum/class.support.php, src/Mail/MailMessage.php, src/Mail/MailTransport.php, tests/ConfigTest.php, tests/MailMessageTest.php, tests/MailTransportTest.php
encapsulate smtp transport use, so it could be (easily) replaced with zend mail component
fixes issues for #234
- removes internal use of PEAR Mail classes
- uses PEAR Mail 1.3.0
- removes preg_replace /e flag use 
originally i planned to replace [Mail_smtp](https://pear.php.net/package/Mail/docs/latest/Mail/Mail_smtp.html) with [Zend\Mail\Transport\Smtp](https://framework.zend.com/manual/2.4/en/modules/zend.mail.transport.html), but that can be done in a separater PR.
=> smtp transport encapsulation

ChangeLog.md, htdocs/css/main.css, htdocs/css/page.css, htdocs/js/page.js, htdocs/manage/custom_field_options.php, lib/eventum/class.custom_field.php, src/Controller/Manage/CustomFieldOptionsController.php, src/Controller/Manage/CustomFieldsController.php, templates/base.tpl.html, templates/manage/custom_field_options.tpl.html, templates/manage/custom_fields.tpl.html, upgrade/patches/64_custom_field_option_order.sql
Historically custom field options have been ordered alphabetically. I've now added the option to order them:
* Alphabetically / Reverse Alphabetically
* Insert / Reverse Insert
* Manually
Custom field options have also been moved to a separate page to allow for ordering and editing.
=> Add option to control how custom field options are ordered.

upgrade/patches/65_isa_self_refs.sql
Some old broken database entries caused `InvalidArgumentException` otherwise:
```
PHP Fatal error: Uncaught exception 'LogicException' in 
src/Model/Repository/IssueAssociationRepository.php:51
```
=> Delete issue association to issue itself. refs #207

composer.json, templates/base.tpl.html
https://github.com/jquery-form/form/releases/tag/v4.0.0
> jQuery Form has a new home! The new canonical URL for the project is https://github.com/jquery-form/form.
> The major version has been incremented to 4 due to the new home of project.
> Version 4 is expected to be backward compatible with 3.51.0.
however. I can not find where do we use this library in templates.
=> replace abandoned malsup/form with jquery-form/form

ChangeLog.md, lib/eventum/class.mail_helper.php, lib/eventum/class.mime_helper.php, lib/eventum/class.routing.php, lib/eventum/class.support.php, src/Mail/Helper/AddressHeader.php, tests/MailHelperTest.php
this one parses input properly. our implementation messed up addresslist with quotes and 8bit data
resulting `Invalid address spec. Unclosed bracket or quotes` errors from PEAR
`Mail_Helper::getEmailAddresses` is now unused, to be dropped later.
the underlying problem was that `Mail_Helper::fixAddressQuoting` corrupted data. it should be ripped out as well.
=> replace buggy Mail_Helper::getEmailAddresses with Zend\Mail based implementation

lib/eventum/class.crm.php, lib/eventum/class.custom_field.php, lib/eventum/class.misc.php, lib/eventum/class.partner.php, lib/eventum/class.workflow.php, lib/eventum/workflow/class.abstract_workflow_backend.php, src/Extension/ExtensionLoader.php, upgrade/patches/39_var_paths.php
ExtensionLoader encapsulates repeated code for loading "backends".
changed also how classes are listed, abstract classes are automatically skipped.
also crm had different naming convention, perhaps allow such breakage and unify it's filename to classname mapping with other backends?
i have no examples how the crm files should be named (documentation did not explain it either).
also crm has such hack, perhaps it could be dropped by defining new standard and naming convention:
```php
$list['class.' . $file . '.php'] = $classname;
```
maybe also move them to namespace `Eventum\CRM` under psr-1:
- lib/eventum/crm/* -> src/CRM/
if so, i'd do that in separate PR
=> add ExtensionLoader class

ChangeLog.md, composer.json, htdocs/js/main.js, templates/base.tpl.html
integrate this [cmd-ctrl-enter.js](https://github.com/widernet/cmd-ctrl-enter/blob/c052c516f630d2155f8de6065751791b9fdd8197/src/cmd-ctrl-enter.js) 666 byte file to bind ctrl (or cmd) enter to submit forms.
=> use ctrl/cmd enter to submit forms

lib/eventum/class.search.php
so that maching custom field value like foo-bar does not result sql
error. it gets quoted as `cf9-foo-bar`
try this again. last time i tried some error occurred.
=> quote custom field names

composer.json, lib/eventum/class.authorized_replier.php, lib/eventum/class.edit_reporter.php, lib/eventum/class.mail_helper.php, lib/eventum/class.note.php, lib/eventum/class.notification.php, lib/eventum/class.routing.php, lib/eventum/class.setup.php, lib/eventum/class.support.php, src/Mail/Helper/AddressHeader.php, tests/MailHelperTest.php
the changes are done, but they need good testing, as i had to assume what some methods return. i.e RAW or QP-encoded. and the results are different, but still valid. however if eventum combines result by it's own then the statement is no longer true.
=> drop Mail_rfc822 PEAR Mail requirement

ChangeLog.md, lib/eventum/class.template_helper.php, src/Templating/UserFile.php, templates/base.tpl.html, templates/include/userscript.tpl.html, templates/include/userstyle.tpl.html
Adds userscript.js, userstyle.css support.
Inspired by DokuWiki implementation.
- https://www.dokuwiki.org/devel:javascript
- https://www.dokuwiki.org/devel:css#user_styles
To add custom JavaScript or custom CSS to every Eventum page,
Place "userscript.js", "userstyle.css" to "config/" dir
and they would be automatically included to every page.
=> add userfile.js, userscript.css support

ChangeLog.md, lib/eventum/class.search.php, templates/list.tpl.html
fix issue listing page:
also don't overwrite iss_expected_resolution_date in model
so be able to compare "0000-00-00" with "0" and get "true".
why it works on view issue page, is that template has extra check:
[templates/view_form.tpl.html:119-124](https://github.com/eventum/eventum/blob/v3.1.10/templates/view_form.tpl.html#L119-L124)
also, seems div class=inline_date_pick does nothing
=> fix expected resolution date being rendered as -1

db/migrations/20170512210935_eventum_extension_class.php, db/migrations/20170512222549_eventum_extension_migrate_db.php, docs/examples/extension/ExampleExtension.php, globals.php, init.php, lib/eventum/class.crm.php, lib/eventum/class.custom_field.php, lib/eventum/class.partner.php, lib/eventum/class.workflow.php, phinx.php, src/Controller/Manage/CustomFieldsController.php, src/Controller/Manage/PartnersController.php, src/Controller/Manage/ProjectsController.php, src/Controller/Manage/UsersController.php, src/Extension/AbstractExtension.php, src/Extension/BuiltinLegacyLoaderExtension.php, src/Extension/ExtensionInterface.php, src/Extension/ExtensionLoader.php, src/Extension/ExtensionManager.php, templates/manage/partners.tpl.html, tests/ExtensionManagerTest.php
The idea is that in setup.php you define path to your extension project.
- Eventum Core will walk over the list
- create class instances
- call registerAutoloader($autoloader) on those classes
in admin views, or places asking for list of workflow classes
- Eventum Core calls `getAvailableWorkflows` and merges the list
when specific workflow is saved in admin, the implementing class would be stored in database (opposed to currently class filename).
so the change is that Workflow/Custom_Field/Partner/CRM can be implemented any class that can be autoloaded. the classes can be available by composer.json or via the `registerAutoload` method.
----
Add new extension to eventum core, add to `config/setup.php` `extensions` entry and implement `ExtensionInterface` methods. `AbstractExtension` is …
=> add extension support for workflows/customfields/partners/crm

CHANGELOG.md, lib/eventum/class.mime_helper.php, lib/eventum/class.misc.php, src/Controller/Setup/SetupController.php
as `zend/mail` and our `mime_helper` require unconditionally `iconv` extension
and `mbstring'` is also used unconditionally in some places in Eventum.
=> require iconv and mbstring extensions

CHANGELOG.md, composer.json, docs/examples/extension/Event/CryptoSubscriber.php, docs/examples/extension/ExampleExtension.php, lib/eventum/class.workflow.php, src/Event/WorkflowEvents.php, src/EventDispatcher/EventManager.php, src/Extension/AbstractExtension.php, src/Extension/ExtensionInterface.php, src/Extension/ExtensionManager.php, tests/Dispatcher/ExtensionSubscribeTest.php
Adds Events to Eventum using [Symfony Event Dispatcher](https://symfony.com/doc/current/components/event_dispatcher.html).
First implementation is handling projectless crypto enable/disable events (#165). I am probably the only one using those workflow methods :)
Example Extension updated with the sample that encrypts/disables `$config['ftp']['password']` field when encryption is turned on/off from administration.
=> add Event/EventDispatcher to Eventum

lib/eventum/class.mail_helper.php, lib/eventum/class.support.php, tests/Mail/MailHelperTest.php
drop formatting for sup_cc, sup_to columns, they are already encoded properly in database.
- [upgrade/patches/62_fixencoding.php](https://github.com/eventum/eventum/blob/v3.2.0/upgrade/patches/62_fixencoding.php)
to my knowledge those fields are used only for display purposes, no need to validate and parse for valid email again
=> drop formatting for sup_cc, sup_to columns

CHANGELOG.md, lib/eventum/class.command_line.php, lib/eventum/class.issue.php, lib/eventum/class.project.php, lib/eventum/class.status.php, src/Controller/CustomFieldsController.php, src/Controller/PostNoteController.php, src/Controller/SendController.php, src/Controller/UpdateController.php, src/Controller/ViewController.php, src/RPC/RemoteApi.php
this is how it should had always been done.
needed by https://github.com/eventum/cli/pull/3
i replaced whatever access checks (`checkIssuePermissions`, `checkIssueAssignment`) there was with `Issue::canUpdate`. this should be sufficient right @balsdorf ?
=> rpc: setIssueStatus: validate parameters server side

CHANGELOG.md, docs/examples/extension/Event/HistorySubscriber.php, docs/examples/extension/ExampleExtension.php, lib/eventum/class.history.php, src/Event/SystemEvents.php, src/Event/UnstructuredEvent.php
just an experiment, is it useful yet, don't know :)
to test, add to `config/setup.php`:
```php
'extensions' => [
'Eventum\\Extension\\ExampleExtension' => dirname(__DIR__) . '/docs/examples/extension/ExampleExtension.php',
],
```
real usecase could be removing irc related code from eventum-core and move it into extension.
or some kind of activity monitor.
=> emit history.add events when history entry is added

CHANGELOG.md, lib/eventum/class.setup.php
drop support for old setup.php formats:
1. $eventum_setup string
2. base64 encoded $eventum_setup_string
3. $ldap_setup
currently all setup files return the array:
- base64 encoded setup was dropped in 2.3.4
- config/setup.php uses return array since 3.0.0
- config/ldap.php uses return array since 3.0.6
but upgrade to 3.3.0 requires that you upgrade to 3.2.0 first, so this backward compat is safe to be dropped.
=> drop support for old setup.php formats

CHANGELOG.md, lib/eventum/class.issue.php, src/RPC/RemoteApi.php
similarly to #280, validate parameters at server side.
i didn't bother to think much, just added similar checks as #280 has:
```php
$this->checkIssuePermissions($issue_id);
$this->checkIssueAssignment($issue_id);
if (!Access::canChangeStatus($issue_id, $usr_id)) {
throw new RemoteApiException("User has no access to update issue #$issue_id");
}
```
also checks if issue is not already closed:
```php
if (Issue::isClosed($issue_id)) {
throw new RemoteApiException("Issue #$issue_id already closed");
}
```
=> rpc: harden closeIssue access checks/validation

contrib/migrate_storage_adapter.php, db/migrations/20170630191008_eventum_attachments.php, db/migrations/20170630200118_eventum_attachments_migrate.php, src/Attachment/Attachment.php, src/Attachment/AttachmentGroup.php, src/Attachment/AttachmentManager.php, src/Attachment/EventumLegacyAdapter.php
This changes the new attachment code to use a new table, `issue_attachment_file_path` to store the flysystem path instead of altering the `issue_attachment_file` table. That alter could take significant time and diskspace, depending on how many attachments you had to migrate. 
refs:
- #300 
- #254
=> Prevent alter table in attachment migration

CHANGELOG.md, src/Mail/MailTransport.php, tests/Mail/GmailTransportTest.php
adds `ssl` option support to `config/setup.php`  with values `tls' or `ssl`. fixes #308
```php
$smtp = [
'from' => 'xyz@domain.cz',
'host' => 'smtp.gmail.com',
'port' => '587',
'ssl' => 'tls',
'auth' => true,
'username' => ...,
'password' => ...,
];
```
additionally sets `ssl=tls` based on `port` value.
=> use ssl=tls for gmail. fixes #308

lib/eventum/class.note.php, src/Controller/ViewNoteController.php, templates/view_note.tpl.html
This prevents users from accessing notes marked as removed as well as documenting why we use `not_removed` instead of actually deleting them.
@glensc , do you think it would be better to actually delete the note if it wasn't routed from an email (i.e. `not_message_id` is blank) ? Another option would be for removed notes set the title and body to be null.
While I was updating code I did some general cleanup such as stop hiding errors and removing code flagged in FIXMEs (once I confirmed it was no longer needed)
=> Prevent users from viewing "removed" notes

lib/eventum/class.mail_helper.php
Mail_Helper::$headers is declared as a string but later used as an
array. PHP 5 would silently change its type to array; PHP 7 raises an
'Illegal string offset' warning instead.
=> Fix mail submission with PHP7

CHANGELOG.md, lib/eventum/class.notification.php
Users with a status of 'inactive' already do not get emails due to the mail queue checking their status before sending. This PR cleans hides them from the NL when viewing an issue. They are still visible if you go to edit the NL.
I've also cleaned up [Notification::getUsersByIssue](https://github.com/eventum/eventum/blob/7ca21595fdaed4f2cbb58b72f3919b5f81f34d72/lib/eventum/class.notification.php#L543) for notes to only return users with a role of Standard User or above. This restriction is already enforced elsewhere in the code but returning all users here is incorrect.
=> Don't show inactive users in notification list

CHANGELOG.md, db/migrations/20171109145542_eventum_custom_filter_multiselect.php, lib/eventum/class.filter.php, lib/eventum/class.search.php, src/Controller/AdvSearchController.php, src/Controller/RssController.php, templates/adv_search.tpl.html, templates/quick_filter_form.tpl.html
* Convert the search fields in the quick filter toolbar and advanced
search to multi-select fields
* For saved searches, store the selection as string of comma-separated
values
* Add DB migration to change column types in `custom_filter` to string
* List of changed fields:
- Assigned (cst_users)
- Category (cst_iss_prc_id)
- Priority (cst_iss_pri_id)
- Product  (cst_pro_id)
- Release  (cst_iss_pre_id)
- Reporter (cst_reporter)
- Severity (cst_iss_sev_id)
- Status   (cst_iss_sta_id)
=> Support multiple selections in search fields

src/Scm/ScmRepository.php
Do not throw an uncaught exception when viewing an issue with commits
from an unknown SCM repository. Just log a warning and display the
commits without links.
=> Gracefully deal with commits from unknown SCM repositories

lib/eventum/smarty/modifier.highlight_quoted.php
When highlighting quoted lines in internal notes, lines containing
nothing except the quote marker are displayed as empty. Since the check
evaluates the line contents as boolean it mistakenly identifies the
string "0" as an empty line.
=> Fix display of quoted lines containing just "0"

lib/eventum/class.support.php, src/Mail/Attachment.php, src/Mail/Helper/DecodePart.php, src/Mail/Helper/TextMessage.php, src/Mail/Helper/WarningMessage.php, src/Mail/MailMessage.php, tests/Mail/AttachmentTest.php, tests/Mail/MailMessageTest.php, tests/Mail/MimeDecodeTest.php, tests/Mail/TextMessageTest.php, tests/data/multipart-mixed-alternative-attachment.eml, tests/data/multipart-mixed-alternative.eml
MailMessage::getMessageBody did not handle email with multipart/mixed with multipart/alternative attachment well.
=> mail message: handle multipart/alternative

CHANGELOG.md, bin/check_reminders.php, bin/download_emails.php, bin/extension.php, bin/ldapsync.php, bin/monitor.php, bin/process_all_emails.php, bin/process_mail_queue.php, bin/truncate_mail_queue.php, src/Console/Application.php, src/Console/Command/Command.php, src/Console/Command/ExtensionEnableCommand.php, src/Console/Command/LdapSyncCommand.php, src/Console/Command/MailDownloadCommand.php, src/Console/Command/MailQueueProcessCommand.php, src/Console/Command/MailQueueTruncateCommand.php, src/Console/Command/MailRouteCommand.php, src/Console/Command/MonitorCommand.php, src/Console/Command/ReminderCheckCommand.php
This allows to add event listeners to console actions:
- [ConsoleEvents::COMMAND Event](https://symfony.com/doc/3.4/components/console/events.html#the-consoleevents-command-event)
- [ConsoleEvents::ERROR Event](https://symfony.com/doc/3.4/components/console/events.html#the-consoleevents-error-event)
- [ConsoleEvents::TERMINATE Event](https://symfony.com/doc/3.4/components/console/events.html#the-consoleevents-terminate-event)
https://symfony.com/doc/3.4/components/console/events.html
example, report memory usage on program shutdown:
```php
$dispatcher->addListener(ConsoleEvents::TERMINATE, function (ConsoleTerminateEvent $event) {
$memoryUsageProcessor = new MemoryUsageProcessor(true);
dump($memoryUsageProcessor([]));
});
```
=> add EventDispatcher to console commands

lib/eventum/auth/APIAuthToken.php, lib/eventum/class.authorized_replier.php, lib/eventum/class.issue.php, lib/eventum/class.notification.php, lib/eventum/class.routing.php, lib/eventum/class.support.php, lib/eventum/irc/BotCommands.php, src/RPC/RemoteApi.php
functional changes:
* 8e774d294 - User::getUserIDByEmail takes plain email only as input, not formatted email header
* 4407ba4ad - reuse sender_usr_id
* 1c781881d - authorized_replier: manualInsert should convert mail header to email first
@balsdorf could you check if the second commit 4407ba4ad is safe to do
=> mail-download: fix user_id fetch using email header

CHANGELOG.md, lib/eventum/class.filter.php, lib/eventum/class.search.php, templates/adv_search_custom_fields.tpl.html
Not sure why this was never implemented before. It just reuses the code path for multiple select.
=> Added support for "checkbox" custom fields on advanced search page

CHANGELOG.md, lib/eventum/class.mail_queue.php, src/Console/Command/MailQueueProcessCommand.php, src/Event/MailQueueListener.php, src/Event/SystemEvents.php, src/EventDispatcher/EventManager.php, src/Mail/MailMessage.php, src/Mail/MailTransport.php
previous version also stopped sending after getting error 21 times.
the previous version kept status=error in database, thus resulting processing only one message at a time if database had any message queue item with status error.
=> mail queue: set message status blocked after 20 retries

src/Controller/RemoteDataController.php
if email is 8bit encoded and contains raw attachment,
htmlspecialchars returns empty string: ""
cc @slay123
=> use ENT_DISALLOWED for htmlspecialchars when displaying email queue

CHANGELOG.md, db/migrations/20180306202659_eventum_maq_message_id.php, lib/eventum/class.mail_queue.php, lib/eventum/class.misc.php, src/Controller/RemoteDataController.php, src/Db/AbstractMigration.php, src/Mail/Helper/MailLoader.php, src/Mail/MailMessage.php
#140 added `maq_message_id` column (released as `3.1.1`), but it was never filled by app itself.
this PR will fill the column in mail queue and restore filling it from `maq_headers` column
```
== 20180306202659 EventumMaqMessageId: migrating
Total 278353 rows, this may take time. Please be patient.
...
== 20180306202659 EventumMaqMessageId: migrated 4261.0148s
All Done. Took 4261.0750s```
NOTE: it's ok to hit `^C` to abort this patch, it can resume if retried.
=> mail_queue: fill maq_message_id column

.gitignore, bin/ci/release.sh, composer.lock
From composer docs:
- projects: [keep lock](https://getcomposer.org/doc/01-basic-usage.md#commit-your-composer-lock-file-to-version-control) in projects where it really matters (production is deployed from it)
- libraries: [do not keep lock](https://getcomposer.org/doc/02-libraries.md#lock-file) for libraries
This will make installation of dependencies faster, especially when switching branches with different dependencies.
There are few things required to be in place, for this to work:
- `config.platform.php` must be set to lowest version supported. this ensures resolvable deps even if developer has newer php version.
- `composer.json` may not be updated manually. use `composer require` or `composer remove` commands. if you forgot to do that, use `composer update --lock`. there may not be …
=> Track composer.lock

CHANGELOG.md, composer.json, composer.lock, db/migrations/20180316174428_eventum_crypto2_upgrade.php, src/Crypto/CryptoException.php, src/Crypto/CryptoKeyManager.php, src/Crypto/CryptoManager.php, src/Crypto/CryptoUpgradeManager.php, src/Crypto/EncryptedValue.php
[php-encryption/2.0.0](https://github.com/defuse/php-encryption/releases/tag/v2.0.0):
> Release of version 2.0.0 of defuse/php-encryption. This is a significant compatibility-breaking improvement over version 1.2.1. See the README for details.
NOTE: as the encrypted results are hex encoded by defuse/php-encryption, instead of base64, the result db columns may need to be increased. 1 byte encryption resulted 170 bytes encrypted result and 255 byte got exploded to 678 bytes.
so therefore not using defuse encoding, but keeping our own base64 implementation
=> update to defuse/php-encryption 2.1

CHANGELOG.md, lib/eventum/class.notification.php
So in [Note::convertNote](https://github.com/eventum/eventum/blob/4e95a61ee6df5c6c8a1fabc5e749e00ea582ab66/lib/eventum/class.note.php#L579) the `$mail` object is passed to `Notification::notifyNewEmail` which changes the sender. Then on [line 588](https://github.com/eventum/eventum/blob/4e95a61ee6df5c6c8a1fabc5e749e00ea582ab66/lib/eventum/class.note.php#L588) `$mail->from` is accessed which now shows the sender from Notification::notifyNewEmail. 
I've now made `notifyNewEmail` create a copy of the mail object before modifying it.
=> Fix bug adding sender to authorized repliers list when unblocking email

CHANGELOG.md, lib/eventum/class.link_filter.php
Fix parsing of link references in markdown.
https://github.com/cebe/markdown/issues/157
=> Fix parsing of link references in markdown

CHANGELOG.md, src/Extension/ExtensionFactoryInterface.php, src/Extension/ExtensionManager.php
this allows extensions create class instances themselves.
for example, I might have event subscriber where I want to inject dependencies via constructor:
```php
class IrcSubscriber implements EventSubscriberInterface {
public function __construct(LoggerInterface $logger) {
$this->logger = $logger;
}
public static function getSubscribedEvents() {
...
```
I'm using myself [Pimple](https://github.com/silexphp/Pimple) [service container](https://pimple.symfony.com/#extending-a-container) to lazy create instances:
```php
$app[IrcSubscriber::class] = function ($app) {
return new IrcSubscriber($app['logger']);
};
```
=> add factory method to extension

CHANGELOG.md, lib/eventum/workflow/class.abstract_workflow_backend.php
the config loading into workflow class was too tightly coupled. if someone needs such logic, they should copy to their own workflow class.
besides, i believe i am the only one who used this feature.
cc @balsdorf
=> deprecate config loading from workflow class

.gitignore, .travis.yml, CHANGELOG.md, autoload.php, config/setup.phpunit.php, db/migrations/20180520134959_eventum_db_charset_config.php, globals.php, htdocs/setup/check_permissions.php, htdocs/setup/index.php, init.php, lib/eventum/auth/class.cas_auth_backend.php, lib/eventum/class.auth.php, lib/eventum/class.language.php, lib/eventum/class.setup.php, src/Console/Command/MonitorCommand.php, src/Controller/Manage/GeneralController.php, src/Controller/Manage/LdapController.php, src/Controller/Manage/MonitorController.php, src/Controller/Manage/ScmController.php, src/Controller/Setup/SetupController.php, src/Crypto/CryptoKeyManager.php, src/Db/Adapter/PdoAdapterBase.php, src/Db/Adapter/YiiAdapter.php, src/Extension/ExtensionManager.php, src/Monolog/Logger.php, tests/AuthCookieTest.php, tests/bootstrap.php
- db: move `APP_CHARSET` to config
- remove most of the `APP_CONFIG_PATH`, `APP_SETUP_FILE` usages
- support for using eventum being itself in vendor (unit tests in projects requiring eventum in composer)
=> Use less global constants

src/Controller/Report/ReportBaseController.php
Little fix for the report date picker to get the correct request vars from the form.
This specifically fixes /reports/workload_date_range.php and /reports/weekly.php which were not getting the start and end dates from the date picker.
=> Fix for reports date picker

CHANGELOG.md, src/Console/Command/MonitorCommand.php
previous monitoring checked only for status='error', this adds 'pending' count monitoring as well.
=> Make mail queue monitoring useful: monitor pending state

db/migrations/20180528141242_eventum_mail_queue_state.php, lib/eventum/class.mail_queue.php, src/Console/Command/MonitorCommand.php, src/Db/AbstractMigration.php
currently when 'pending' or 'error' mails count reaches 50, further mails are not processed
=> update db state when mail queue item failed max retries

CHANGELOG.md, contrib/migrate_storage_adapter.php
i got disk full error while migrating. with previous testing it (migration) was rather unreliable (not atomic commit).
so wanted to know which attachments got broken state.
```
root@eventum ~/eventum# ./contrib/migrate_storage_adapter.php local --verify
Verifying data in 'local://' Adapter
Preparing temporary table. Please wait...
Verifying 5302 file(s)
```
=> storage adapter: add verify option

CHANGELOG.md, lib/eventum/class.support.php, templates/notifications/bounced_email.tpl.text
1. remove $original_message from bounced_email.tpl, it is never filled. the changes introduced from:
* e5d9bb42a - add template for bounceMessage() (10 years ago) <Elan Ruusamäe>
* 2d79d6849 - add bounceMessage(), not used yet (10 years ago) <Elan Ruusamäe>
2. fix date type for bounced email template
=> Fix bounce emails not to produce errors

CHANGELOG.md, src/Console/Command/MailDownloadCommand.php, src/Mail/Exception/InvalidMessageException.php, src/Mail/Helper/MailLoader.php, src/Mail/MailMessage.php
the uncaught exception made one faulty email stop email download process
```
In Address.php line 41:
The input is not a valid email address. Use the basic format local-part@hostname
```
the faulty email was:
```
From: "Benny   Higgins " <>
```
=> Handle uncaught header exception from mail download

src/Mail/Helper/MailLoader.php, tests/Mail/LoadEmailTest.php, tests/data/92367.txt
This makes it possible to still load emails, whose headers can't be parsed.
The headers are named with `X-Broken-Header-` prefix
=> Mail: Rename unparseable headers

bin/migrate_storage_adapter.php, src/Console/Command/AttachmentMigrateCommand.php
makes more sense if you look at the usage:
Verify:
```
$ ./bin/migrate_storage_adapter.php --verify legacy
Verifying data in 'legacy://' Adapter
Preparing temporary table. Please wait...
Verifying 1516 file(s)
```
Perform actual migration:
```
$ ./bin/migrate_storage_adapter.php --yes pdo local --limit=100
Migrating data from 'pdo://' to 'local://'
Preparing temporary table. Please wait...
Moving 1 file(s)
1/1 [============================] 100% < 1 sec/< 1 sec 6.8 MiB (93046: pdo://102959/93046.docx)
You might need to run 'OPTIMIZE TABLE attachment_chunk' to reclaim space from the database
```
=> attachment migrate: rename --yes to --migrate

CHANGELOG.md, src/Event/Subscriber/IrcSubscriber.php, src/Event/Subscriber/MailQueueListener.php, src/Event/SystemEvents.php, src/EventDispatcher/EventManager.php, src/Extension/IrcNotifyExtension.php
This is useful from workflow to test different eventum versions.
It's quite common for me to pre-test some eventum branch while using same workflow setup.
cc @balsdorf
=> Add SystemEvents::hasEvent to feature test availability

CHANGELOG.md, src/Extension/ExtensionManager.php
for example I had event subscriber missing slack token
cc @balsdorf
=> extension loader: skip components that fail to initialize

CHANGELOG.md, src/Attachment/AttachmentGroup.php, src/Attachment/AttachmentManager.php
fixes: #412
the problem was caused by mispatched less than operator
```diff
- ($usr_id != $group->user_id && User::getRoleByUser($usr_id, Issue::getProjectID($group->issue_id) < User::ROLE_MANAGER))
+ ($usr_id != $group->user_id && User::getRoleByUser($usr_id, Issue::getProjectID($group->issue_id)) < User::ROLE_MANAGER)
```
the bugs were introduced by:
- ff310a91c8a508e5e3c68b287fce364f91e0e4d1
- 1d49286a35af4c049daef16584a295ddb8a1c1b6
simplified code to use local variables
cc @balsdorf, @lmoralesa
=> Fix attachment delete permissions check

CHANGELOG.md, composer.json, composer.lock, db/migrations/20170427170945_eventum_init_database.php, db/migrations/20170512193942_eventum_flysystem_pdo.php, db/migrations/20170512210935_eventum_extension_class.php, db/migrations/20170630191008_eventum_attachments.php, db/migrations/20170920202640_eventum_sup_header_length.php, db/migrations/20171109145542_eventum_custom_filter_multiselect.php, db/migrations/20180501205449_eventum_irc_notice_indices.php, src/Db/AbstractMigration.php
https://github.com/cakephp/phinx/releases/tag/v0.10.0
bumps `"php": ">=5.4"` to `"php": ">=5.6"` (irrelevant to us, we require 5.6 already)
```
- Installing cakephp/core (3.6.4): Loading from cache
- Installing cakephp/utility (3.6.4): Loading from cache
- Installing cakephp/datasource (3.6.4): Loading from cache
- Installing cakephp/cache (3.6.4): Loading from cache
- Installing cakephp/database (3.6.4): Loading from cache
- Installing cakephp/collection (3.6.4): Loading from cache
- Updating robmorgan/phinx (0.9.2 => 0.10.0): Loading from cache
```
probably merge in 3.6.0
=> Update phinx to 0.10

src/Mail/Helper/MailLoader.php, tests/Mail/LoadEmailTest.php
Email viewer (view_email.php) fails with an exception "Invalid header name detected"
if a stored raw email starts with a Mbox line "From name@example.com .." which is
not a correct mail header.
Sample email tests/data/from_nocolon.txt may be used as a test case.
=> Detect invalid mail header starting with "From " and replace it with a correct custom one.

CHANGELOG.md, lib/eventum/auth/AuthCookie.php, lib/eventum/class.email_account.php, lib/eventum/class.issue_lock.php, lib/eventum/class.misc.php, lib/eventum/class.project.php, lib/eventum/class.search_profile.php, src/RPC/XmlRpcServer.php
PHP 7.0 adds `allowed_classes` element of options to be able to specify which classes may be instantiated.
See:
- http://php.net/unserialize
cc @balsdorf
=> Secure unserialize: control allowed_classes options

CHANGELOG.md, src/Console/Command/MailDownloadCommand.php, tests/Mail/MailHelperTest.php
> Cannot set a default value when using `InputOption::VALUE_NONE` mode
Fixes: https://github.com/mnapoli/silly/issues/51
=> mnapoli/silly: fix for boolean commandline arguments

CHANGELOG.md, src/Mail/Helper/TextMessage.php, src/Mail/MailMessage.php, tests/Mail/TextMessageTest.php, tests/data/email-106251.txt
Thus it's a mail without any mime extensions.
cc @astabing
=> TextMessage: do not parse subparts if no content-type given

CHANGELOG.md, config/config.dist.php, db/migrations/20170428180919_eventum_initial_data.php, db/migrations/20190115211455_eventum_auth_adapter_setup.php, htdocs/manage/auth.php, init.php, lib/eventum/auth/APIAuthToken.php, lib/eventum/class.auth.php, src/Auth/Adapter/AdapterInterface.php, src/Auth/Adapter/CasAdapter.php, src/Auth/Adapter/ChainAdapter.php, src/Auth/Adapter/Factory.php, src/Auth/Adapter/LdapAdapter.php, src/Auth/Adapter/MysqlAdapter.php, src/Auth/AuthException.php, src/Auth/Ldap/LdapConnection.php, src/Auth/PasswordHash.php, src/Console/Command/LdapSyncCommand.php, src/Controller/Manage/AuthController.php, src/Controller/Manage/LdapController.php, src/Controller/Manage/ManageBaseController.php, src/Db/Adapter/AdapterInterface.php, src/Setup/DatabaseSetup.php, templates/help/ldap.tpl.html, templates/manage/auth.tpl.html, templates/manage/ldap.tpl.html, templates/manage/manage.tpl.html, tests/PasswordAuthTest.php, tests/bootstrap.php
Allow auth adapters setup from config:
the default:
```php
'auth' => [
'adapter' => MysqlAdapter::class,
],
```
with chain adapter with ldap and mysql:
```php
'auth' => [
'adapter' => ChainAdapter::class,
'options' => [
ChainAdapter::class => [
0 => [
LdapAdapter::class,
MysqlAdapter::class,
],
],
],
],
```
=> Allow auth adapters to be chained

CHANGELOG.md, db/migrations/20190127204900_eventum_login_back_off_config.php, init.php, lib/eventum/class.auth.php, src/Auth/Adapter/AdapterInterface.php, src/Auth/Adapter/CasAdapter.php, src/Auth/Adapter/ChainAdapter.php, src/Auth/Adapter/LdapAdapter.php, src/Auth/Adapter/MysqlAdapter.php, src/Auth/AuthException.php, src/Controller/LoginController.php, src/Controller/RssController.php
Move Login-Back-Off logic to MySQL adapter only: It makes no sense for other adapters than MySQL and they've implemented methods as dummy anyway. The external systems likely account themselves such logic.
The major concern was that the accounting was `usr_id` based, meaning unknown users are not accounted, to resolve that would need another table, which seems too much for now.
This also moves constants to setup config:
- `APP_FAILED_LOGIN_BACKOFF_COUNT`
- `APP_FAILED_LOGIN_BACKOFF_MINUTES`
refs:
- https://github.com/eventum/eventum/commit/780ddaa822866c432b97d92adfff3934a70eaa01
- https://github.com/eventum/eventum/pull/441#issuecomment-455273425
- https://github.com/eventum/eventum/pull/441#issuecomment-456530674
cc @balsdorf
=> Move Login-Back-Off logic to MySQL adapter only

CHANGELOG.md, composer.json, composer.lock, lib/eventum/class.setup.php, src/Config/ConfigPersistence.php, tests/Config/ConfigPersistenceTest.php
Benefit: writes configs with short PHP array syntax. More compact and readable result.
cc @balsdorf
=> Use symfony/var-exporter for writing config files

CHANGELOG.md, lib/eventum/class.user.php, src/Auth/Adapter/MysqlAdapter.php, src/RPC/XmlRpcServer.php
Resolves problem that system user failed login count keeps increasing:
- https://github.com/eventum/eventum/pull/455#issuecomment-460016804
altho there are no logs why it fail.
I also thought to disable `usr_last_login`/`usr_last_failed_login`/`usr_failed_logins` updating as these were added for login backoff functionality: 796a62d.
But then thought these are useful for audit purposes anyway. But then again, these aren't updated for non-mysql backends, sigh...
=> xmlrpc: verify token first to avoid incrementing failed logins

lib/eventum/class.date_helper.php
- https://www.reddit.com/r/ISO8601/comments/8lkcns/the_php_iso8601_date_format_is_not_actually/
- http://php.net/manual/en/class.datetimeinterface.php#datetime.constants.iso8601
the differences are:
```php
const ISO8601 = 'Y-m-d\TH:i:sO';
const ATOM    = 'Y-m-d\TH:i:sP';
```
http://ee1.php.net/manual/en/function.date.php#refsect1-function.date-parameters
format character | Description | Example returned values
-- | -- | --
O | Difference to Greenwich time (GMT) in hours  | Example: +0200
P | Difference to Greenwich time (GMT) with colon between hours and minutes (added in PHP 5.1.3)  | Example: +02:00
=> use DateTime::ATOM as DateTime::ISO8601 is not iso8601 compatible

CHANGELOG.md, src/Controller/Report/OpenIssuesController.php
Fix open issues reports generated by open_issues.php. Set default number of days to be excluded to zero and sanitize human input with casting to integer.
=> Fix open issues report: set default number of days to exclude

CHANGELOG.md, src/Mail/Helper/TextMessage.php, src/Mail/MailMessage.php, tests/Mail/TextMessageTest.php, tests/data/gnus511.txt
Emacs Gnus 5.11 mail messages with attachments are bounced. Eventum
fails to parse it correctly. This PR provide a sample email message.
=> Add buggy email message from Emacs Gnus 5.11

CHANGELOG.md, composer.json, composer.lock, src/Mail/Helper/TextMessage.php, tests/data/message-chopped.txt
While the horde one formats without spaces: `">"` instead of expected `"> "`, this is better than current, as current seems broken.
See: https://github.com/eventum/eventum/issues/478#issuecomment-466972484
cc @vladsf
=> use Horde_Text_Flowed to unflow text

AUTHORS, CHANGELOG.md, lib/eventum/class.support.php, lib/eventum/search/class.sphinx_fulltext_search.php
Loading a full email body, parsing headers, attachments is
irrelevant for the search results. This change improves speed
and eliminates possible exceptions thrown on a full email load.
IMPORTANT:
As a contributor I must add Oracle Copyright notice to the place designated for such notices (AUTHORS).
=> Remove email parser overhead on search

composer.lock
```
Package operations: 0 installs, 15 updates, 0 removals
- Updating symfony/filesystem (v4.2.3 => v4.2.4): Loading from cache
- Updating symfony/config (v4.2.3 => v4.2.4): Loading from cache
- Updating symfony/console (v4.2.3 => v4.2.4): Loading from cache
- Updating symfony/event-dispatcher (v4.2.3 => v4.2.4): Loading from cache
- Updating symfony/http-foundation (v4.2.3 => v4.2.4): Loading from cache
- Updating symfony/options-resolver (v4.2.3 => v4.2.4): Loading from cache
- Updating symfony/ldap (v4.2.3 => v4.2.4): Loading from cache
- Updating symfony/security-core (v4.2.3 => v4.2.4): Loading from cache
- Updating symfony/security-csrf (v4.2.3 => v4.2.4): Loading from cache
- Updating symfony/serializer (v4.2.3 => …
```
=> update package dependencies

CHANGELOG.md, composer.json, composer.lock, lib/eventum/class.link_filter.php, lib/eventum/class.workflow.php, lib/eventum/workflow/class.abstract_workflow_backend.php, src/Controller/ListController.php, src/Controller/UpdateController.php, src/Controller/ViewController.php, src/Event/ResultableEvent.php, src/Event/SystemEvents.php, src/LinkFilter/IssueLinkFilter.php, src/LinkFilter/LinkFilter.php, src/LinkFilter/LinkFilterInterface.php, src/LinkFilter/ProjectLinkFilter.php, tests/LinkFilterTest.php
More workflow methods can be replaced by using events.
In fact, I can drop my workflow class.
=> Add more events to handle Workflow calls

CHANGELOG.md, lib/eventum/class.custom_field.php, lib/eventum/class.search.php, src/Model/Entity/CustomField.php, src/Model/Entity/UserPreference.php, src/Model/Repository/IssueAssociationRepository.php, src/Model/Repository/Traits/GetOneTrait.php, tests/CustomField/CustomFieldTest.php, tests/CustomField/CustomFieldTypesTest.php, tests/CustomField/TestCase.php, tests/Db/DoctrineTest.php, tests/DoctrineTraits.php, tests/src/TestCase.php
Refs:
- #466
- https://tideways.com/profiler/blog/5-doctrine-orm-performance-traps-you-should-avoid
=> Add caching to custom fields

CHANGELOG.md, phinx.php, src/Event/SystemEvents.php
Example:
```php
class PhinxConfig implements EventSubscriberInterface
{
public static function getSubscribedEvents(): array
{
return [
SystemEvents::PHINX_CONFIG => 'phinxConfig',
];
}
public function phinxConfig(GenericEvent $event): void
{
$phinx = $event->getArguments();
$phinx['paths']['migrations'][] = $this->getMigrationPath();
$event->setArguments($phinx);
}
```
=> Add event to be able to configure Phinx config

CHANGELOG.md, lib/eventum/class.filter.php, lib/eventum/class.search.php
```
[2019-04-10 14:12:42] app.ERROR: Uncaught Exception TypeError:
"Argument 1 passed to Eventum\Model\Repository\CustomFieldRepository::getListByProject() must be of the type integer, string given
[stacktrace]
lib/eventum/class.filter.php(943): Eventum\Model\Repository\CustomFieldRepository->getListByProject('', 1, NULL)
#1 lib/eventum/class.filter.php(581): Filter::getFiltersInfo()
#2 src/Controller/RssController.php(177): Filter::getDetails(158, false)
#3 src/Controller/BaseController.php(82): Eventum\Controller\RssController->prepareTemplate()
#4 htdocs/rss.php(17): Eventum\Controller\BaseController->run()
#5 {main}
```
Fixes several mistakes down the path.
=> Fx fatal errors when opening rss feeds

CHANGELOG.md, docs/examples/extension/ExampleExtension.php, src/Console/Command/ExtensionEnableCommand.php, src/Extension/AbstractExtension.php, src/Extension/BuiltinLegacyLoaderExtension.php, src/Extension/ExtensionFactoryInterface.php, src/Extension/ExtensionManager.php, src/Extension/IrcNotifyExtension.php, src/Extension/Provider/AutoloadProvider.php, src/Extension/Provider/CrmProvider.php, src/Extension/Provider/CustomFieldProvider.php, src/Extension/Provider/ExtensionProvider.php, src/Extension/Provider/FactoryProvider.php, src/Extension/Provider/PartnerProvider.php, src/Extension/Provider/SubscriberProvider.php, src/Extension/Provider/WorkflowProvider.php
- Deprecates `AbstractExtension` and `ExtensionInterface`
- Breaks compatibility: parameter and return type hints are required now
This allows writing single-purpose extensions:
- an extension providing only `SubscriberProvider` interface
cc @balsdorf
=> Split extension features to each interface

CHANGELOG.md, bin/ci/configure.sh, composer.json, composer.lock, lib/eventum/class.setup.php, src/Console/Command/ExtensionEnableCommand.php, src/Extension/ExtensionManager.php, src/Extension/XhguiProfilerExtension.php
To enable this extension, you need to register it first:
```
$ ./bin/extension.php src/Extension/XhguiProfilerExtension.php 'Eventum\Extension\XhguiProfilerExtension'
Enabling extension: \Eventum\Extension\XhguiProfilerExtension
```
NOTE: This adds `ext-mongodb` requirement for development.
If don't want mongodb, can just tell composer to ignore it:
```
composer config platform.ext-mongodb 1.4.3
```
cc @balsdorf @lauripiisang
=> Add support for enabling xhgui-profiler

CHANGELOG.md, composer.json, composer.lock, src/Markdown.php, tests/MarkdownTest.php, tests/data/markdown/autolink.html, tests/data/markdown/autolink.md, tests/data/markdown/h5-details.html, tests/data/markdown/headers.html, tests/data/markdown/linkrefs.html, tests/data/markdown/table.html, tests/data/markdown/tasklist.html
This prevents the page being loaded partially when unclosed `<script>` (for example) is included in issue body.
Currently have to allow 'HTML.Trusted' to make tasklist `<input>` html work:
```php
// allow tasklist <input> checkboxes
$config->set('HTML.Trusted', true);
```
This is no worse than the current solution (not filtering at all). Making more strict html validation can be done later.
=> Sanitize HTML with htmlpurifier

CHANGELOG.md, lib/eventum/class.filter.php, lib/eventum/class.search.php
https://github.com/eventum/eventum/pull/393 changed `cst_custom_field ` serialization from `serialize` to `json_encode`, but this caused wrong data type, when it was previously array, it's now `stdClass`, and templates can't handle that:
on `adv_search.php?custom_id=1`:
```
[2019-04-22 23:07:37] app.ERROR: Uncaught Exception Error: "Cannot use object of type stdClass as array" at /Users/glen/scm/eventum/eventum/var/cache/5f42ad00d36c4e9912c1dbb8862f873575e473ae_0.file.adv_search.tpl.html.php line 95 {"exception":"[object] (Error(code: 0): Cannot use object of type stdClass as array at /Users/glen/scm/eventum/eventum/var/cache/5f42ad00d36c4e9912c1dbb8862f873575e473ae_0.file.adv_search.tpl.html.php:95)
```
this PR changes seralization to use arrays.
unclear how migration was handled in to …
=> Use array json decode for cst_custom_field

CHANGELOG.md, src/Scm/Adapter/Gitlab.php
in case of issue deletion the description in payload is NULL
`{"code":-1,"message":"Argument 1 passed to Eventum\\IssueMatcher::match() must be of the type string, null given, called in /src/Scm/Adapter/Gitlab.php on line 98"}`
```json
{
"object_kind": "issue",
"event_type": "issue",
...
"object_attributes": {
"author_id": 68,
"closed_at": null,
"confidential": false,
"created_at": "2019-05-09 15:23:45 +0300",
"description": null,
```
=> GitLab: skip issue matching on empty text

CHANGELOG.md, composer.json, composer.lock, src/Mail/MailMessage.php, tests/Mail/MailMessageTest.php, tests/data/in-reply-to.txt
Refs: #426
```
Package operations: 1 install, 6 updates, 1 removal
- Removing zendframework/zend-servicemanager (2.4.13)
- Updating zendframework/zend-stdlib (2.4.13 => 3.2.1): Loading from cache
- Updating zendframework/zend-config (2.4.13 => 3.2.0): Loading from cache
- Updating zendframework/zend-validator (2.4.13 => 2.11.0): Loading from cache
- Updating zendframework/zend-mime (2.4.13 => 2.7.1): Loading from cache
- Updating zendframework/zend-loader (2.4.13 => 2.6.0): Loading from cache
- Installing true/punycode (v2.1.0): Loading from cache
- Updating zendframework/zend-mail (dev-develop-2.4 cbabc38 => 2.10.0):  Checking out d7beb63d5f
```
need to ensure the changes present in our 2.4 fork are present upstream:
- …
=> Update zend-mail to 2.10

composer.lock
```
Loading composer repositories with package information
Package operations: 0 installs, 25 updates, 0 removals
- Updating symfony/contracts (v1.1.0 => v1.1.1): Loading from cache
- Updating symfony/console (v4.2.8 => v4.2.9): Loading from cache
- Updating symfony/routing (v4.2.8 => v4.2.9): Loading from cache
- Updating symfony/http-foundation (v4.2.8 => v4.2.9): Loading from cache
- Updating symfony/event-dispatcher (v4.2.8 => v4.2.9): Loading from cache
- Updating symfony/debug (v4.2.8 => v4.2.9): Loading from cache
- Updating symfony/http-kernel (v4.2.8 => v4.2.9): Loading from cache
- Updating symfony/finder (v4.2.8 => v4.2.9): Loading from cache
- Updating symfony/filesystem (v4.2.8 => v4.2.9): Loading from cache
- …
```
=> composer: update dependencies

CHANGELOG.md, composer.lock, src/Mail/Exception/InvalidMessageException.php, src/Mail/MailMessage.php, tests/Mail/LoadEmailTest.php, tests/data/110616.txt
Internal error of zend-mail causes mail download to abort: https://github.com/zendframework/zend-mail/pull/230
And eventum internally creates another type error by unable to convert the type.
```
app.ERROR: E_RECOVERABLE_ERROR: Object of class Zend\Mail\Headers could not be converted to string {"code":4096,"message":"Object of class Zend\\Mail\\Headers could not be converted to string","file":"/Users/glen/scm/eventum/eventum/src/Mail/Helper/MailLoader.php","line":73} {"file":null,"line":null,"class":null,"function":"preg_replace","memory_usage":"6 MB","memory_peak_usage":"6 MB","version":"dev-master-g5992f433c","usr_id":""}
PHP Catchable fatal error:  Object of class Zend\Mail\Headers could not be converted to string in /Users/glen/scm/eventum/eventum/src/Mail/Helper/MailLoader.php on …
```
=> Fix loading emails with semicolon in name field

CHANGELOG.md, db/migrations/20190803221836_eventum_add_indexes.php
Enabled slow log without indexes. This is indexes added from my database instance.
- add index: `support_email.sup_message_id`
=> Add missing database indexes

CHANGELOG.md, db/migrations/20181231121638_eventum_utf8_mb4.php, db/migrations/20181231125822_eventum_utf8_mb4_convert.php, phinx.php
NOTE:
- MySQL >= 5.5.3 is required after this PR
- MySQL >= 5.7 is recommended: https://mysqlserverteam.com/mysql-8-0-when-to-use-utf8mb3-over-utf8mb4/
- Requires [`db/migrations/20180520134959_eventum_db_charset_config.php`](https://github.com/eventum/eventum/blob/v3.5.0/db/migrations/20180520134959_eventum_db_charset_config.php) be applied (Eventum `3.5.0`)
Changes:
- https://mathiasbynens.be/notes/mysql-utf8mb4
- https://kittmedia.com/2017/running-gitlab-with-utf8mb4-and-mysql-5-5-and-5-6/
cc @balsdorf
=> Change charset to utf8mb4 of support_email and issue tables

lib/eventum/class.misc.php, src/Extension/ExtensionLoader.php
The existing code is faulty, not checking errors properly:
```
app.ERROR: Uncaught Exception TypeError: "readdir() expects parameter 1 to be resource, bool given" at /home/travis/build/eventum/eventum/lib/eventum/class.misc.php line 375 {"exception":"[object] (TypeError(code: 0): readdir() expects parameter 1 to be resource, bool given at /home/travis/build/eventum/eventum/lib/eventum/class.misc.php:375)
[stacktrace]
#0 /home/travis/build/eventum/eventum/lib/eventum/class.misc.php(375): readdir(false)
#1 /home/travis/build/eventum/eventum/src/Extension/ExtensionLoader.php(85): Misc::getFileList('/home/travis/bu...')
#2 /home/travis/build/eventum/eventum/src/Extension/BuiltinLegacyLoaderExtension.php(88): Eventum\\Extension\\ExtensionLoader->getClassList()
```
=> Replace Misc::getFileList with Symfony Finder

CHANGELOG.md, docs/examples/extension/ExampleExtension.php, src/Extension/ClassLoader.php, src/Extension/ExtensionManager.php, src/Extension/Provider/AutoloadProvider.php
This adds stable interface to Extensions and method to load "autoload.files"
```php
use Eventum\Extension\ClassLoader;
use Eventum\Extension\Provider;
class ExampleExtension implements
Provider\AutoloadProvider
{
/**
* Method invoked so the extension can setup class loader.
*
* @param ClassLoader $loader
*/
public function registerAutoloader($loader): void
{
[$classmap, $psr0, $psr4, $files] = $this->getComposerAutoload();
// add classmap
$loader->addClassMap($classmap);
// add namespaces (psr-0)
foreach ($psr0 as $namespace => $path) {
$loader->add($namespace, $path);
}
// add namespaces (psr-4)
foreach ($psr4 as $namespace => $path) {
$loader->addPsr4($namespace, $path);
}
// add files
foreach ($files as $fileIdentifier => $file) {
$loader->autoloadFile($fileIdentifier, $file);
}
}
```
=> Extensions: Add Proxy to Composer Autoloader

CHANGELOG.md, templates/base.tpl.html
this allows adding project specific user javascript (`config/userscript.js`) to the page:
```javascript
$(document).ready(function($) {
if (window.project && window.project.id === 1) {
// do some stuff
}
});
```
refs:
- https://github.com/eventum/eventum/issues/652
=> Expose project/issue id to window globals

CHANGELOG.md, lib/eventum/class.group.php, src/Controller/UpdateController.php
```
E_WARNING: count(): Parameter must be an array or an object that implements Countable
```
- https://www.php.net/manual/en/migration72.incompatible.php#migration72.incompatible.warn-on-non-countable-types
=> Fix PHP 7.2 count() warnings

CHANGELOG.md, src/Config/ConfigPersistence.php, src/Controller/Manage/EncryptionController.php, src/Crypto/CryptoKeyManager.php, src/Crypto/CryptoUpgradeManager.php, src/Opcache.php
Finally resolved this bug:
Having `secret_key.php` or `setup.php` cached in any way,
when enabling/disabling encryption,
creates inconsistency and breaks the enable/disable
=> Invalidate opcache when changing crypto state

CHANGELOG.md, db/migrations/20190925202208_eventum_merge_ldap_config.php, lib/eventum/class.setup.php
Now kept in main `config/setup.php` file.
=> Drop support for storing ldap config in separate config

CHANGELOG.md, htdocs/js/page.js, lib/eventum/class.search.php, templates/list.tpl.html
I every was disgruntled cause it was too complicated to looking for all issues states in lot of projects . So I modified my issues list. I added checkbox to view all projects issue next to "hide closed" one, when user_role >= developer. 
Would be interest to merge this feature?
Thanx for discuss and proposals for modification
=> Feature: show all projects checkbox in issues list

composer.json, composer.lock, src/HtmlConverter.php, src/Setup/RequirementNotSatisfiedException.php, src/Setup/Requirements.php
Adds support via [league/html-to-markdown](https://packagist.org/packages/league/html-to-markdown) to convert html to markdown.
requires new extensions:
- ext-xml
- ext-dom
NOTE: the class is not used yet, but merged to have new dependencies in place
=> Add support for converting html to markdown

composer.lock
```
Package operations: 1 install, 33 updates, 0 removals
- Updating symfony/thanks (v1.1.0 => v1.2.4): Loading from cache
- Updating cakephp/collection (3.8.5 => 3.8.6): Loading from cache
- Updating cakephp/core (3.8.5 => 3.8.6): Loading from cache
- Updating cakephp/utility (3.8.5 => 3.8.6): Loading from cache
- Updating cakephp/log (3.8.5 => 3.8.6): Loading from cache
- Updating cakephp/datasource (3.8.5 => 3.8.6): Loading from cache
- Updating cakephp/cache (3.8.5 => 3.8.6): Loading from cache
- Updating cakephp/database (3.8.5 => 3.8.6): Loading from cache
- Updating doctrine/cache (1.9.1 => 1.10.0): Loading from cache
- Updating symfony/routing (v4.3.8 => v4.4.1): Loading from cache
- Updating symfony/debug (v4.3.8 => …
```
=> Update all composer dependencies

CHANGELOG.md, htdocs/css/main.css
This makes long notes not to break UI of notes listing.
cc @slay123
=> Add CSS overflow to notes view

README.md
Links to MySQL mailing lists are not working.  No reference to Eventum at MySQL.
=> README: Remove links to MySQL mailing lists

CHANGELOG.md, src/Controller/PostNoteController.php, src/Controller/SendController.php
This makes the list of allowed next statuses when posting an internal
note consistent with the other views (view issue, update issue and
bulk update).
=> Use allowed statuses from workflow when writing notes or emails

CHANGELOG.md, htdocs/css/main.css
Eventum always had weird tiny fonts, makes pretty annoying especioally retina displays.
This CSS I've got long time ago from @slay123.
=> Increase font size on the pages

composer.json, composer.lock, src/Markdown.php
This allows using new extensions:
- Added new Heading Permalink extension (https://github.com/thephpleague/commonmark/pull/420)
- Added new Table of Contents extension (https://github.com/thephpleague/commonmark/issues/441)
=> Update league/commonmark to 1.4.0

CHANGELOG.md, composer.lock, res/assets/sass/all.scss, res/assets/sass/markdown.scss, src/Markdown.php, tests/data/markdown/headers.html, tests/data/markdown/inline.html, tests/data/markdown/table.html
Continuation from #816, adds [Heading Permalink extension].
[Heading Permalink extension]: https://commonmark.thephpleague.com/1.4/extensions/heading-permalinks/
Probably needs to be context-aware:
- different prefix for issue body and notes
uses `'inner_contents' => '¶'` as default `<svg>` is stripped out by htmlpurifier:
- https://github.com/thephpleague/commonmark/pull/458
=> Add heading permalink markdown extension

CHANGELOG.md, composer.json, composer.lock, init.php, src/Controller/Manage/CustomFieldsController.php, src/Controller/Manage/PartnersController.php, src/Controller/Manage/ProjectsController.php, src/Controller/Manage/UsersController.php, src/EventDispatcher/EventManager.php, src/Extension/ExtensionManager.php, src/Extension/Provider/ServiceProvider.php, src/Kernel.php, src/ServiceContainer.php, src/ServiceProvider/ServiceProvider.php, tests/Scm/TestCase.php
Add [Pimple] - A simple PHP Dependency Injection Container, as it's what I'm familiar with.
[Pimple]: https://pimple.symfony.com/
Changing later to PSR11 container, for example [Symfony Service Container], is smaller task than refactoring code to use containers and DI in general.
[Symfony Service Container]: https://symfony.com/doc/4.4/service_container.html
=> Add Pimple based service container

CHANGELOG.md, db/migrations/20200505135053_register_legacy_extensions.php, db/migrations/20200506031942_eventum_register_audit_trail_extension.php, lib/eventum/class.access.php, lib/eventum/class.workflow.php, lib/eventum/workflow/class.abstract_workflow_backend.php, src/Controller/Manage/GeneralController.php, src/Event/SystemEvents.php, src/Extension/AuditTrailExtension.php, src/Extension/Legacy/CustomerLegacyExtension.php, src/Extension/Legacy/WorkflowLegacyExtension.php, src/Extension/RegisterExtension.php
This also moves some log issue access to AuditTrailExtension extension. you can disable the extension to completely remove it's use.
=> Add ACCESS_ISSUE event for checking issue access

CHANGELOG.md, lib/eventum/class.setup.php, src/Monolog/AppInfoProcessor.php, src/Monolog/MailHandler.php
If `email_error` handler is enabled, this adds error message to email subject making it easier to filter messages.
=> Add error message to email error reports

.envrc, .travis.yml, CHANGELOG.md, bin/releng/build-release.sh, composer.json, composer.lock, package.json, webpack.mix.js, yarn.lock
replace long deprecated component-installer.
it's getting on a way of various things.
example, locked to old symfony/process:
```
$ composer why symfony/process
kriswallsmith/assetic  v1.4.0  requires  symfony/process (~2.1|~3.0)
$ composer why kriswallsmith/assetic
robloach/component-installer  0.2.3  requires  kriswallsmith/assetic (1.*)
```
This replaces most of the packages, keeping same version. missing (ctrl-alt-del) or complicated (jquery-ui) packages left for the future replacement.
refs:
- https://github.com/RobLoach/component-installer/pull/101
- https://github.com/kriswallsmith/assetic/issues/882
=> Use npm packages instead of component installer

CHANGELOG.md, docs/examples/extension/Subscriber/IssuePercentageUpdater.php, lib/eventum/class.access.php, lib/eventum/class.authorized_replier.php, lib/eventum/class.issue.php, lib/eventum/class.notification.php, lib/eventum/class.support.php, lib/eventum/class.workflow.php, lib/eventum/workflow/class.abstract_workflow_backend.php, src/Controller/AssociateController.php, src/Event/EventContext.php, src/Event/ResultableEvent.php, src/Event/SystemEvents.php, src/Extension/Legacy/WorkflowLegacyExtension.php
This way if your installation does not use Workflow, you can completely skip loading `WorkflowLegacyExtension`.
NOTE: EventDispatcher added in #272
=> Move workflow handling to WorkflowLegacyExtension extension

CHANGELOG.md, bin/check_reminders.php, bin/download_emails.php, bin/export-issues.php, bin/extension.php, bin/ldapsync.php, bin/migrate_storage_adapter.php, bin/monitor.php, bin/process_all_emails.php, bin/process_mail_queue.php, bin/truncate_mail_queue.php, src/Console/Application.php, src/Console/Command/AttachmentMigrateCommand.php, src/Console/Command/ExportIssuesCommand.php, src/Console/Command/ExtensionEnableCommand.php, src/Console/Command/LdapSyncCommand.php, src/Console/Command/MailDownloadCommand.php, src/Console/Command/MailQueueProcessCommand.php, src/Console/Command/MailQueueTruncateCommand.php, src/Console/Command/MailRouteCommand.php, src/Console/Command/MonitorCommand.php, src/Console/Command/ReminderCheckCommand.php, src/ServiceContainer.php, src/ServiceProvider/ConsoleCommandsService.php
To lazy init, and most importantly release `::execute()` name for symfony/cli compatibility.
=> Use container for Silly console application

CHANGELOG.md, composer.json, composer.lock, htdocs/js/main.js, htdocs/js/page.js, package.json, res/assets/scripts/Cookie.js, res/assets/scripts/bootstrap.js, templates/email_drafts.tpl.html, webpack.mix.js, yarn.lock
The usage is rather minimal:
```
➔ git grep -F '.cookie'
composer.lock:                        "jquery.cookie.js"
htdocs/js/main.js:    $.cookie('visibility_' + id, display, {expires: Eventum.expires});
htdocs/js/page.js:    $.cookie('visibility_' + id, display, {expires: Eventum.expires});
templates/email_drafts.tpl.html:    $.cookie('show_all_drafts', showValue, { expires: Eventum.expires });
templates/email_drafts.tpl.html:        <input type="checkbox" name="show_all_drafts" id="show_all_drafts" value="1" {if $smarty.cookies.show_all_drafts|default:0 == 1}checked{/if} onClick="showAllDrafts(this)"><label for="show_all_drafts">{t}Show All Drafts{/t}</label>
webpack.mix.js:    'htdocs/components/jquery-cookie/jquery.cookie.js',
```
When implementing, prefer composition over inheritance: …
=> Replace jquery-cookie with a js-cookie npm module

CHANGELOG.md, src/Console/Command/AttachmentMigrateCommand.php, src/Console/Command/Command.php, src/Console/Command/ExportIssuesCommand.php, src/Console/Command/ExtensionEnableCommand.php, src/Console/Command/LdapSyncCommand.php, src/Console/Command/MailDownloadCommand.php, src/Console/Command/MailQueueProcessCommand.php, src/Console/Command/MailQueueTruncateCommand.php, src/Console/Command/MailRouteCommand.php, src/Console/Command/MonitorCommand.php, src/Console/Command/ReminderCheckCommand.php, src/Console/ConsoleTrait.php
The commands now available via `bin/console.php` as well:
```
➔ git grep const.DEFAULT_COMMAND
src/Console/Command/AttachmentMigrateCommand.php:    public const DEFAULT_COMMAND = 'attachment:migrate';
src/Console/Command/ExportIssuesCommand.php:    public const DEFAULT_COMMAND = 'export:issues';
src/Console/Command/ExtensionEnableCommand.php:    public const DEFAULT_COMMAND = 'extension:enable';
src/Console/Command/LdapSyncCommand.php:    public const DEFAULT_COMMAND = 'ldap:sync';
src/Console/Command/MailDownloadCommand.php:    public const DEFAULT_COMMAND = 'mail:download';
src/Console/Command/MailQueueProcessCommand.php:    public const DEFAULT_COMMAND = 'mail-queue:process';
src/Console/Command/MailQueueTruncateCommand.php:    public const DEFAULT_COMMAND = 'mail-queue:truncate'; …
```
=> Make commands available from Symfony Console

composer.json, composer.lock, res/bundles.php, res/packages/dev/monolog.yml, res/packages/prod/monolog.yml, res/packages/test/monolog.yml, src/Console/Command/AttachmentMigrateCommand.php, src/Console/Command/ExportIssuesCommand.php, src/Console/Command/ExtensionEnableCommand.php, src/Console/Command/LdapSyncCommand.php, src/Console/Command/ListCommand.php, src/Console/Command/MailDownloadCommand.php, src/Console/Command/MailQueueProcessCommand.php, src/Console/Command/MailQueueTruncateCommand.php, src/Console/Command/MailRouteCommand.php, src/Console/Command/MonitorCommand.php, src/Console/Command/ReminderCheckCommand.php
This improves coloring and var dumper for context arguments.
The Symfony console commands are prefixed with eventum now:
```
➔ ./bin/console.php -e prod
Symfony 4.4.8 (env: prod, debug: false)
Usage:
command [options] [arguments]
Options:
-h, --help            Display this help message
-q, --quiet           Do not output any message
-V, --version         Display this application version
--ansi            Force ANSI output
--no-ansi         Disable ANSI output
-n, --no-interaction  Do not ask any interactive question
-e, --env=ENV         The Environment name. [default: "prod"]
--no-debug        Switches off debug mode.
-v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug
Available commands:
eventum …
```
=> Setup symfony/monolog-bundle for improved console error logging

docs/examples/extension/Auth/NullAuthAdapter.php, docs/examples/extension/ExampleExtension.php, src/Auth/Adapter/ChainAdapter.php, src/Auth/Adapter/Factory.php, src/Controller/Manage/AuthController.php, src/Extension/ExtensionManager.php, src/Extension/Provider/AuthAdapterProvider.php
Allows an extension to provide class names that implement `Auth\Adapter\AdapterInterface`.
```php
<?php
namespace Example;
use Eventum\Extension\ClassLoader;
use Eventum\Extension\Provider;
use Example\Auth\NullAuthAdapter;
/**
* Example Eventum Extension.
*
* To enable this extension, write to config/setup.php:
*
* 'extensions' => [
*   'Eventum\\Extension\\ExampleExtension' => '/path/to/this/file/ExampleExtension.php',
* ],
*/
class ExampleExtension implements Provider\AuthAdapterProvider
{
/**
* Return class names implementing Auth\Adapter\AdapterInterface
*
* @return string[]
* @see \Eventum\Extension\Provider\AuthAdapterProvider
*/
public function getAvailableAuthAdapters(): array
{
return [
NullAuthAdapter::class,
];
}
}
```
Refs:
- https://github.com/eventum/eventum/issues/847
=> Allow choosing Auth adapters from Extension provides

CHANGELOG.md, lib/eventum/class.email_account.php, lib/eventum/class.support.php
Missed a similar scenario when deleting email account:
- https://github.com/eventum/eventum/pull/206
This is also probably too slow, to execute, and would require manual cleanup (optimize tables) if someone really wants to deleted emails related to an email account.
=> Remove dangerous feature: removing emails when deleting email account

src/Controller/CloseController.php
The privilege check in CloseController is insufficient, it does not
verify that the user actually has permissions to update the issue. A
user with 'Viewer' or 'Reporter' role can close issues by entering the
close.php URL.
=> Fix privilege check when closing issues

CHANGELOG.md, res/assets/scripts/Eventum.js, src/Controller/RemoteDataController.php, templates/add_phone_entry.tpl.html, templates/bulk_update.tpl.html, templates/include/new_form.tpl.html, templates/manage/email_responses.tpl.html, templates/manage/faq.tpl.html, templates/manage/news.tpl.html, templates/post_note.tpl.html, templates/update_form.tpl.html
Implement Markdown preview and add a help link for the Markdown syntax
to the following text areas:
- New/update issue description
- Internal note
- Bulk close message
- Phone call description
- Manage news
- Manage internal FAQ
- Manage canned email responses
Notes:
- This is pretty basic and has room for improvement, but it works pretty well.
- I'm unsure about the (mis)use of `RemoteDataController` which is otherwise only used for expandable cells.
=> Markdown preview and help link

CHANGELOG.md, lib/eventum/class.issue.php
If a matching category or priority was found in the target project the
new values were accidentally not applied. This feature was broken since
commit 019bb91d.
=> Fix category/priority mapping when moving an issue between projects

.travis.yml, CHANGELOG.md, bin/releng/bump.sh, composer.json, composer.lock, docs/wiki/Upgrading.md
- PHP 7.1 is [EOL] since 1 Dec 2019.
- Updating to 7.2 allows us to [upgrade Symfony components to 5.1][1]
- Allows to update [phinx to 0.12][2]
- I've been using 7.2 in production for quite a while
- The current recommended PHP version is 7.3
[EOL]: https://www.php.net/eol.php
[1]: https://github.com/symfony/symfony/blob/v5.1.2/composer.json#L19
[2]: https://github.com/cakephp/phinx/blob/0.12.1/composer.json#L28
=> Update PHP requirement to 7.2

CHANGELOG.md, lib/eventum/class.link_filter.php, src/Event/SystemEvents.php, src/Markdown/CommonMark/UserLookup.php, src/Markdown/CommonMark/UserMentionGenerator.php, src/Markdown/Markdown.php, src/Markdown/MarkdownRenderer.php, src/Markdown/MarkdownRendererInterface.php, src/ServiceContainer.php, src/ServiceProvider/MarkdownServiceProvider.php, tests/MarkdownTest.php
This is internal cleanup. Moves Markdown instantiation to ServiceProvider.
=> Move Markdown code to own namespace

CHANGELOG.md, composer.json, composer.lock, lib/eventum/class.issue.php
Use [symfony/deprecation-contracts][1] to note down deprecations.
[1]: https://packagist.org/packages/symfony/deprecation-contracts
=> Add Symfony Deprecation contracts to mark deprecations

CHANGELOG.md, composer.json, composer.lock, phinx.php
- https://github.com/cakephp/phinx/releases/tag/0.12.0
- https://github.com/cakephp/phinx/releases/tag/0.12.1
- https://github.com/cakephp/phinx/releases/tag/0.12.2
- https://github.com/cakephp/phinx/releases/tag/0.12.3
=> Update Phinx to 0.12

bin/console.php, bin/upgrade.php, init.php, src/Kernel.php
This makes default installation to use production mode.
This may need to call cache clear which was not necessary before:
```
$ bin/console.php cache:clear
```
=> Use APP_ENV=prod by default

.gitattributes, CHANGELOG.md, composer.json, composer.lock, symfony.lock
Setup `symfony/flex` (dev only), but it has side effect:
- the generated vendor/autoload.php has PHP version check:
```
➔ head vendor/autoload.php
<?php
if (\PHP_VERSION_ID < 70200) {
echo sprintf("Fatal Error: composer.lock was created for PHP version 7.2.5 or higher but the current PHP version is %d.%d.%d.\n", PHP_MAJOR_VERSION, PHP_MINOR_VERSION, PHP_RELEASE_VERSION);
exit(1);
}
```
I've tried to accomplish that check with composer 2.0 initially:
- https://github.com/eventum/eventum/pull/873
but it proved to be more difficult to achieve.
=> Enable PHP version check in vendor/autoload.php

CHANGELOG.md, lib/eventum/class.setup.php
This was removed in #686 (Eventum 3.8.3) and is no longer needed.
=> Drop loading deprecated ldap.php

CHANGELOG.md, src/Event/ConfigUpdateEvent.php, src/EventDispatcher/EventManager.php, tests/Dispatcher/ExtensionSubscribeTest.php
"Symfony\Component\EventDispatcher\Event" is deprecated since Symfony 4.3, use "Symfony\Contracts\EventDispatcher\Event" instead.
refs:
- https://symfony.com/blog/new-in-symfony-4-3-simpler-event-dispatching
- https://www.drupal.org/project/drupal/issues/3055198
- https://www.drupal.org/project/drupal/issues/3153803
- https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2971
- https://jira.ez.no/browse/EZP-30828
=> Use Symfony\Contracts\EventDispatcher\Event instead of deprecated Symfony\Component

CHANGELOG.md, lib/eventum/class.auth.php, lib/eventum/class.custom_field.php, lib/eventum/class.setup.php, lib/eventum/class.support.php, lib/eventum/class.user.php, res/monolog.yml, res/packages/dev/monolog.yml, res/packages/prod/monolog.yml, src/Logger/LoggerTrait.php, src/ServiceContainer.php
Configure Symfony same way as monolog-cascade logger:
- add processors
- add error mail handler
Extracted from https://github.com/eventum/eventum/pull/898 to be able to merge sooner.
=> Configure Symfony logger: Processors, MailHandler

CHANGELOG.md, db/migrations/20200818114141_eventum_fix_null_notes.php, lib/eventum/class.note.php
Uncaught Exception TypeError: "Argument 1 passed to Eventum\Mail\MailMessage::createFromString() must be of the type string, null given,
called in lib/eventum/class.note.php on line 97 at src/Mail/MailMessage.php line 103
[stacktrace]
#0 lib/eventum/class.note.php(97): Eventum\\Mail\\MailMessage::createFromString(NULL)
#1 lib/eventum/search/class.sphinx_fulltext_search.php(150): Note::getDetails(175541)
#2 lib/eventum/class.search.php(788): Sphinx_Fulltext_Search->getExcerpts()
#3 lib/eventum/class.search.php(424): Search::getFullTextExcerpts(Array)
#4 src/Controller/ListController.php(163): Search::getListing(1, Array, 0, 15)
#5 src/Controller/BaseController.php(84): Eventum\\Controller\\ListController->prepareTemplate()
#6 htdocs/list.php(17): Eventum\\Controller\\BaseController->run() …
=> Fix creating mail message on null note

lib/eventum/class.user.php
That's a weird filtering logic, but at least the notice accessing false as array is gone now.
=> Fix notices with php 7.4 when user has no roles

templates/base.tpl.html, templates/sentry.tpl.html
Workaround for mis-use of {block}, {extends} and {include}: https://github.com/smarty-php/smarty/issues/303 which results of certain block on the page ({javascripts} from users_list.tpl) being repeated twice.
=> Add workaround for Manage users dataTable error

CHANGELOG.md, res/assets/sass/main.scss
Revert fab53a1 and apply better.
The selector was too loose and applied unwanted selectors:
- https://github.com/eventum/eventum/pull/794#issuecomment-677665278
Fixes https://github.com/eventum/eventum/issues/916, https://github.com/eventum/eventum/issues/942
=> Fix assignment field and quick search dropdowns

CHANGELOG.md, lib/eventum/class.filter.php
Commit 5bb5631be changed the serialization of custom field filter
parameters from PHP array syntax to JSON syntax, but missed one
occurrence in the function building the URLs for sorting links. As a
result custom field filters are lost when changing the sort order by
clicking one of the list headings.
x-ref:
- https://github.com/eventum/eventum/pull/393
- https://github.com/eventum/eventum/pull/530
=> Fix sorting links when searching for custom fields

.github/workflows/tests.yml, .travis.yml, composer.json, phinx.php, tests/Generic/MarkdownTest.php, tests/travis/setup.php
Travis integration has become totally unbearable recently:
- jobs wait queue is very long, some hours or even days
- status updates are no longer updated in PRs
- inconsistent and old composer versions, making it very difficult to have a consistent environment for different PHP versions. for example, unwanted upgrade to v2 and force to use v1 requires hack as `--1` flag not supported on composer 1.8
🙇 Thank you Travis-CI for being out there for that long, but it is time to switch...
This migrates CI jobs for pull requests to GitHub Actions, the release step is still run in Travis CI.
Inspired by my previous work:
- https://github.com/perftools/xhgui/pull/366
refs:
- https://github.com/actions/toolkit/blob/main/docs/commands.md#environment-files
=> Use GitHub Actions for CI integration

CHANGELOG.md, src/Mail/Imap/ImapConnection.php
Fixes notices like E_WARNING: imap_expunge() expects parameter 1 to be resource, null given.
=> Avoid calling imap methods on null

CHANGELOG.md, res/assets/sass/page.scss
If email/note is added long `<code>` block, it will mess up whole layout.
cc @slay123
=> Wrap large code blocks in note and email view

CHANGELOG.md, lib/eventum/class.link_filter.php, res/assets/scripts/Eventum.js, src/Controller/BaseController.php, src/Kernel.php, src/LinkFilter/LinkFilter.php, src/LinkFilter/LinkFilterInterface.php, src/ServiceContainer.php, src/ServiceProvider/ServiceProvider.php, templates/add_phone_entry.tpl.html, templates/bulk_update.tpl.html, templates/include/new_form.tpl.html, templates/post_note.tpl.html, templates/update_form.tpl.html
This allows LinkFilters that rendered view in `view.php` relying on `issue_id` POST value now be able to render same in preview mode.
=> Add Request context to LinkFilter callbacks

CHANGELOG.md, res/assets/scripts/app.js
To support timestamps in the future, use the `allowFuture` setting:
```js
jQuery.timeago.settings.allowFuture = true;
```
=> Allow timeago to have future timestamps

CHANGELOG.md, res/packages/doctrine.yml
User Deprecated: Creating Doctrine\ORM\Mapping\UnderscoreNamingStrategy
without making it number aware is deprecated and will be removed in
Doctrine ORM 3.0.
Creating Doctrine\ORM\Mapping\UnderscoreNamingStrategy without making it
number aware is deprecated and will be removed in Doctrine ORM 3.0.
- https://stackoverflow.com/questions/58975182/deprecation-doctrine-orm-mapping-underscorenamingstrategy-without-making-it-num
- https://github.com/doctrine/orm/blob/2.8.x/UPGRADE.md#deprecated-number-unaware-doctrineormmappingunderscorenamingstrategy
- https://github.com/symfony/recipes/blob/af59c6fed6ae2d8929f9ac3a1b9d280a3ebfbfbc/doctrine/doctrine-bundle/2.0/config/packages/doctrine.yaml
=> Use underscore_number_aware naming_strategy for Doctrine

res/assets/scripts/Validation.js
#963 
- https://github.com/eventum/eventum/blob/master/res/assets/scripts/Validation.js#L146-L156
```js
isValidDate(field_prefix) {
const selected_date = new Date();
selected_date.setMonth(Eventum.getField(field_prefix + '[Month]').val() - 1);
selected_date.setDate(Eventum.getField(field_prefix + '[Day]').val());
selected_date.setYear(Eventum.getField(field_prefix + '[Year]').val());
return selected_date.getDate() === Eventum.getField(field_prefix + '[Day]').val();
};
```
typeof(selected_date.getDate() ) is number
typeof(Eventum.getField(field_prefix + '[Day]').val()) is string
Function isValidDate is never true in strict comparing. Solution may be retype getField().val() to number and rebuild app.js, I think.
=> Time tracking - Eventum still says "Please select a valid date of work"

CHANGELOG.md, src/Mail/Helper/TextMessage.php, tests/Mail/TextMessageTest.php, tests/data/html-part-encoding.txt
Parts of multipart MIME messages are often sent in quoted-printable
or base64 encoding. Use the DecodePart helper to decode them based on
their Content-Transfer-Encoding header. This was already done for
text/plain parts, but not for others like text/html.
=> Fix decoding of non-plaintext parts in multipart mails

CHANGELOG.md, templates/post_note.tpl.html
Debug slipped in from 96cb66163fa7bd3b8aba084761e7692c226bca41 via #989
The debug resulted weird snippets appearing at the end of notes:
for replies:
```
[
]
```
for new notes:
```
asd[
]
```
=> Fix: Remove post note debug

CHANGELOG.md, composer.json, composer.lock, src/ServiceProvider/MarkdownServiceProvider.php, symfony.lock
Uses https://github.com/giberti/commonmark-emoji-extension until https://github.com/thephpleague/commonmark/pull/546 is ready.
Did not feel necessary to make this configurable, so this is always enabled.
Can do that later if people request or complain.
=> Add emoji parsing to markdown areas

bin/releng/configure.sh
No longer used as of #358 (3.4.0)
=> Cleanup ext-mcrypt, no longer used with defuse/php-encryption 2.x

.github/workflows/ci.yml, .travis.yml, CHANGELOG.md, bin/releng/Dockerfile, composer.json, composer.lock, docs/wiki/Prerequisites.md, docs/wiki/Upgrading.md, symfony.lock
Update required php version to 7.3 to be able to update laminas-mail 2.14:
- https://github.com/laminas/laminas-mail/pull/140
Tasks
=> Update PHP requirement to 7.3

init.php, res/services.php, src/Auth/Adapter/Factory.php, src/Controller/Manage/CustomFieldsController.php, src/Controller/Manage/PartnersController.php, src/Controller/Manage/ProjectsController.php, src/Controller/Manage/UsersController.php, src/EventDispatcher/EventManager.php, src/Extension/ExtensionManager.php, src/Extension/Legacy/WorkflowLegacyExtension.php, src/Kernel.php, src/ServiceContainer.php, src/ServiceProvider/ServiceProvider.php, tests/Scm/TestCase.php, tests/TestCase.php, tests/bootstrap.php
Addendum to https://github.com/eventum/eventum/pull/1025.
This ensures `ExtensionManager` is final and testable. Somehow #1025 CI passed and merged prematurely event tests were broken.
This attempts to really fix the cyclic loop that #1025 introduced with a small tradeoff of backward-incompatible change.
Extensions should not access things from container in their constructor. Such access must be delayed, for example use `LazyPropertiesTrait`: fcb1fbd6ae9210312c7e9e1c71f03ecae9c7415c
=> Refactor ExtensionManager to take extensions list from constructor

CHANGELOG.md, lib/eventum/class.setup.php, src/Controller/Manage/GeneralController.php, src/Extension/SlackExtension.php, templates/manage/general.tpl.html, templates/manage/general/slack.tpl.html
Can be enabled in Settings -> General:
Requires:
- https://github.com/eventum/eventum/pull/898
- https://github.com/eventum/eventum/pull/1025
=> Add Extension to report errors to Slack channel

CHANGELOG.md, db/migrations/20200710050147_eventum_register_scm_extension.php, res/routes.yml, src/Controller/Manage/ScmController.php, src/Extension/ExtensionManager.php, src/Extension/ScmExtension.php, tests/Scm/TestCase.php
If the extension is not enabled, the `/scm_ping` route will be missing.
=> Move SCM setup to Extension

CHANGELOG.md, init.php, lib/eventum/class.history.php, lib/eventum/class.issue.php, lib/eventum/class.mail_queue.php, lib/eventum/class.notification.php, lib/eventum/class.reminder_action.php, lib/eventum/class.routing.php, lib/eventum/class.setup.php, lib/eventum/class.template_helper.php, lib/eventum/class.user.php, lib/eventum/class.workflow.php, phinx.php, src/Console/Application.php, src/Crypto/CryptoUpgradeManager.php, src/EventDispatcher/EventManager.php, src/Mail/ImapMessage.php, src/Model/Repository/CommitRepository.php, src/Scm/Adapter/Gitlab.php, src/ServiceContainer.php, src/ServiceProvider/MarkdownServiceProvider.php, src/ServiceProvider/ServiceProvider.php, tests/CustomField/CustomFieldTest.php, tests/Scm/ScmControllerTest.php, tests/Scm/TestCase.php
Extracted from https://github.com/eventum/eventum/pull/966.
This picks change from https://github.com/eventum/eventum/pull/966 other than the ones creating dependency loop. Proxy EventManager methods into ServiceContainer for future changes.
=> Deprecate EventManager class

CHANGELOG.md, src/Crypto/CryptoKeyManager.php, src/Crypto/CryptoManager.php, src/Crypto/EncryptedValue.php, tests/Crypto/CryptoTest.php
We want that exceptions thrown from crypto subsystem throw `Eventum\Crypto\CryptoException`
This worked if `Defuse\Crypto\Exception\CryptoException` was thrown, but not its subclasses.
=> Fix catching Defuse CryptoException

CHANGELOG.md, phpunit.xml, res/packages/test/twig.yml
The "twig.exception_controller" configuration key has been deprecated in
Symfony 4.4, set it to "null" and use "framework.error_controller"
configuration key instead.
- https://github.com/symfony/symfony/blob/4.4/UPGRADE-4.4.md#twigbundle
- https://github.com/symfony/symfony/issues/34493
=> Fix twig deprecation

CHANGELOG.md, src/ServiceProvider/MarkdownServiceProvider.php
The `inner_contents` config option is deprecated; use `symbol` instead:
- https://github.com/thephpleague/commonmark/pull/506
=> Fix markdown heading_permalink deprecation

CHANGELOG.md, lib/eventum/class.auth.php, lib/eventum/class.misc.php, src/Mail/MessageIdGenerator.php
Deprecate use of `ircmaxell/random-lib`, use [random_bytes](https://www.php.net/random_bytes) from php 7.0
=> Use random_bytes() rather RandomLib library

CHANGELOG.md, src/Controller/Ajax/DynamicCustomFieldController.php
`/ajax/dynamic_custom_field.js.php?form_type=report_form`:
> Uncaught LogicException: Access to EntityManagerInterface forbidden when Kernel is booting
refs: #1026
=> Fix DynamicCustomFieldController accessing repository too soon

CHANGELOG.md, src/Db/AbstractMigration.php
This re-uses existing code for typical lazy-init use.
=> Refactor: Add LazyProperties to AbstractMigration

.github/workflows/ci.yml, bin/releng/Dockerfile, bin/releng/build-release.sh, bin/releng/dist.sh, bin/releng/tools.sh
This should speed up the build by using a pre-built docker image for the release process.
Before: 8m: https://github.com/eventum/eventum/runs/2252437914
After: 3m: https://github.com/eventum/eventum/pull/1043/checks?check_run_id=2261951583
=> Use pre-built docker image

composer.json, composer.lock
The original version pinning was due composer/package-versions-deprecated
being pulled which was incompatible at the time.
```
- Updating composer/package-versions-deprecated (1.5.1 => 1.8.0): Loading from cache
- Updating doctrine/orm (v2.7.3 => 2.7.5): Loading from cache
```
=> Unlock doctrine/orm v2.7.3

.travis.yml, composer.lock
Fix Travis release after https://github.com/eventum/eventum/pull/1043.
We still use Travis to make snapshot and releases.
=> Travis: Use pre-built image

composer.json, composer.lock, symfony.lock
inverts https://github.com/eventum/eventum/pull/1054 because `doctrine/dbal` 2.13.0 breaks debugbar integration:
- https://github.com/doctrine/dbal/issues/4603
so downgrade to 2.12.1.
NOTE: we must have a unit test to cover this before attempting to update again.
=> Downgrade doctrine/dbal (2.13.0 => 2.12.1)

CHANGELOG.md, src/Controller/Ajax/DynamicCustomFieldController.php, src/Controller/Helper/RepositoryHelper.php
Apparently can't have two __get() handlers:
- lazy properties
- controller helpers
So, use existing 'repository' helper to get access to CustomFieldRepository.
This is another fix to #1041
=> Fix 500 error on /ajax/dynamic_custom_field.js.php?form_type=report_form

CHANGELOG.md, templates/time_tracking_entry.tpl.html
Error was caught by Sentry integration ;)
```
ReferenceError: makeDate is not defined
at HTMLFormElement.validateTimeForm (/time_tracking.php:197:14)
at HTMLFormElement.dispatch (/js/components.js:1:28262)
at HTMLFormElement._.handle (/js/components.js:1:24974)
at HTMLFormElement.r (/js/raven.js:1:4665)
```
Testing:
1. add time entry, set start time in future
2. add time entry, set end time in the future
=> Fix JavaScript error on Add time tracking page

CHANGELOG.md, src/Controller/BaseController.php, src/Controller/Helper/HelperTrait.php
This replaces one magic with another magic, which is maybe less magical, but still magical.
This allows controllers to define lazy properties without conflicting with base lazy properties:
```php
private $lazyProperties = ['fieldname', 'fieldname2'];
```
=> Add HelperTrait to register all lazy properties

.github/workflows/ci.yml
This avoids error like:
- https://github.com/fastify/github-action-merge-dependabot/issues/27
=> Update fastify/github-action-merge-dependabot v1 -> v2.0.0

CHANGELOG.md, src/Mail/Helper/MimePart.php
Fixes https://github.com/eventum/eventum/issues/1068
Testing:
1. open issue in eventum web
2. click send email button on bottom of the page
3. in the popup window choose attach a file (attachment area)
4. send the email
5. in refreshed issue view page click on the email that was just sent
6. from there download the attachment
7. compare the attachment md5 with the file that was uploaded
=> Fix attachments corruption when attached to emails from web

CHANGELOG.md, tests/Scm/TestCase.php
```
6x: Method Doctrine\ORM\EntityManager::detach() is deprecated and will be removed in Doctrine ORM 3.0.
6x in CommitTest::setUp from Eventum\Test\Scm
```
refs:
- https://github.com/eventum/eventum/runs/2231927632?check_suite_focus=true
=> Resolve Doctrine ORM 3.0 EntityManager::detach deprecation

.github/workflows/ci.yml
refs:
- https://github.com/fastify/github-action-merge-dependabot/commit/8ddd309b3f1e89233ff236e2c7fa9fd4f212e5ef
> ⚠️UPGRADE NEEDED
>  
> **Version v2.0.0 will stop working on 1st August 2021**. If you are using version v2.0.0, you must upgrade to the latest version.
=> Update fastify/github-action-merge-dependabot 2.0.2 -> v2.1.1

CHANGELOG.md, res/assets/scripts/app.js
Hide the search input on single selects if there are 10 or fewer options.
=> Hide the search input on single selects if there are 10 or fewer options

docs/examples/extension/ExampleExtension.php
`ExampleExtension` class is defined in `Example` namespace so fix the namespaced reference and the file path hardcoded in the 
extension loader function.
=> Use correct namespace and path for the extension example

docs/examples/extension/ExampleExtension.php
Current Example extension path is almost hard coded in the autoloader function. 
Moving ExampleExtension outside docs/ causes hard to understand errors.
=> Remove hard coded extension path from Example extension

CHANGELOG.md, src/Auth/Adapter/LdapAdapter.php
Make "Inactive DN" parameter optional as the [Help](https://github.com/eventum/eventum/blob/a149ed43f345c17570ce3aadeb4d819b81333d10/docs/help/ldap.md) page says. 
Eventum hides "Customize LDAP Config" page if the parameter is not set. `bin/console.php eventum:ldap:sync` fails as well.
=> Make "Inactive DN" parameter optional as the Help page says

CHANGELOG.md, src/Console/Command/LdapSyncCommand.php
Skip LDAP user entries with no single valid email. This patch adds a loose check there is at least one valid email.
=> Add loose email validation in LdapSyncCommand

CHANGELOG.md, lib/eventum/class.user.php
Do not send email notice if user password is not set. 
If user accounts are created outside Eventum e.g. in LDAP and then ldapsync'ed then there is no reason to send email notice with
empty password.
=> Make user notification on account creation optional

CHANGELOG.md, docs/examples/extension/Console/Command/ExampleHelloCommand.php, docs/examples/extension/config/services.yml, src/Console/Command/ExampleHelloCommand.php
Here is an example command I trying to add to a release of Eventum, but I get 
the error:
```
[eventumtest Command]$ /eventum/bin/console.php eventum:example:hello
There are no commands defined in the "eventum:example" namespace.
..
```
Not sure I understand how to add custom console commands.
=> Add example command for extension

CHANGELOG.md, src/Console/Command/LdapSyncCommand.php
LdapSyncCommand lacks an option to search and disable Eventum users which are not found in LDAP Active DN. Current code expects to find inactive users in Inactive DN.
This patch proposes --disable-missed option to check active Eventum users against LDAP. Users which are not found in Active DN to be set inactive.
=> LdapSyncCommand: disable users missing in LDAP Active DN

CONTRIBUTING.md
How to keep forked Eventum even with the upstream
=> Docs: How to keep forked Eventum even with the upstream

CHANGELOG.md, lib/eventum/class.search.php
Check sort_by value before query
Check the sort_by value in the request with the default table before entering the query.
Fix bug Time-Based Blind SQL Injection
- Disclosure: https://huntr.dev/bounties/668789af-8781-461c-99bb-d159e5a1d877/
=> Fix `sort_by` not being filtered in search form

CHANGELOG.md, package.json, webpack.mix.js, yarn.lock
Revert "Bump jquery-ui from 1.12.1 to 1.13.0 (#1240)"
It's not compatible, for example view issue page has such errors on console:
```
jquery-ui.js?id=44a2af31b10434ff00c4:3226 Uncaught TypeError: $.uniqueSort is not a function
at processClassString (jquery-ui.js?id=44a2af31b10434ff00c4:3226)
at $.<computed>.<computed>._classes (jquery-ui.js?id=44a2af31b10434ff00c4:3239)
at $.<computed>.<computed>._toggleClass (jquery-ui.js?id=44a2af31b10434ff00c4:3276)
at $.<computed>.<computed>._addClass (jquery-ui.js?id=44a2af31b10434ff00c4:3264)
at $.<computed>.<computed>._create (jquery-ui.js?id=44a2af31b10434ff00c4:15110)
at $.<computed>.<computed>._create (jquery-ui.js?id=44a2af31b10434ff00c4:2834)
at $.<computed>.<computed>._createWidget (jquery-ui.js?id=44a2af31b10434ff00c4:3032)
at new …
```
=> Lock jquery-ui to 1.12.x

CHANGELOG.md, lib/eventum/class.db_helper.php, lib/eventum/class.misc.php, lib/eventum/class.search.php, src/Controller/ListController.php
Followup to https://github.com/eventum/eventum/pull/1252:
The fix didn't account for custom fields and resulted sql error in case of invalid input, which resulted a 500 page.
The new fix, field is validated against the list from the adv_search template only when not using custom fields:
- https://github.com/eventum/eventum/blob/81fbd075b12ba32b01c4720c1408672e034d54f9/templates/adv_search.tpl.html#L155-L162
Also, the `$sort_by` is now escaped with `quoteIdentifier` (method for columns) rather `escape` (method for values)
=> Fix invalid input for advanced search sort_by

CHANGELOG.md, src/Extension/ExtensionManager.php
This allows clean up extensions needing to provide factory method that just do lookup from container:
```php
public function factory($className)
{
$services = self::getServiceContainer();
if (isset($services[$className])) {
return $services[$className];
}
return null;
}
```
=> Feature: Use ServiceContainer first when finding classes for extensions

.github/workflows/ci.yml, .travis.yml, CHANGELOG.md, bin/releng/Dockerfile, bin/releng/build-release.sh, bin/releng/composer-replace.sh, bin/releng/tools.sh, bin/releng/update_timestamps.sh, composer.json, composer.lock, symfony.lock
Using replace is nice way to minimize vendor size,
but it also makes it very difficult to install dependencies
when eventun/eventum is being used as "packages-dev"
The major obstacle is that "replace" may be provided by only one package
the way composer thinks.
The "replace" works fine when used as project, but we also want to use
eventum as library, for example extension development
=> Fix: Drop "replace" keys from composer.json

.dockerignore, .gitattributes, .github/workflows/ci.yml, bin/releng/Dockerfile, bin/releng/build-release.sh, src/Version.php
This utilizes stages for build, thus allowing parallel execution and cache on rebuilds
```bash
APP_VERSION=$(git describe --tags --match=v*)
docker build . -f bin/releng/Dockerfile --build-arg=APP_VERSION=${APP_VERSION#v} --target=out -o out --progress=plain
```
```
$ ls -lh out/*
-rw-r--r-- 1 root root 49M Dec 13 04:09 out/eventum-3.10.9-74-ge4a6118f8.tar
```
=> Feature: Add support for building release tarball with Dockerfile stages

.github/workflows/ci.yml
- https://github.com/fastify/github-action-merge-dependabot/tree/5983205c569917cd35ba9dfec8858236c74cd86a#how-to-upgrade-from-2x-to-new-3x
- https://github.com/fastify/github-action-merge-dependabot/pull/107
=> Update fastify/github-action-merge-dependabot to v3.0.0

CHANGELOG.md, lib/eventum/class.workflow.php, src/Mail/ProcessMailMessage.php
This allows to have workflow event to delete email:
```php
/**
* Ignore emails from being processed
*/
public function blockIncomingMail(GenericEvent $event): void
{
/** @var ImapMessage $mail */
$mail = $event->getSubject();
if (!in_array($mail->getSender(), self::BLOCK_SENDERS, true)) {
return;
}
$event->stopPropagation();
$this->debug('Stopped mail from {}', ['sender' => $mail->getSender()]);
$dumper = new MailDumper(self::DUMP_PATH);
$dumper->dump($mail);
/** @var ImapConnection $connection */
$connection = $event['connection'];
$connection->deleteMessage($mail);
}
```
=> Feature: Add $connection to MAIL_PROCESS_BEFORE event

bin/releng/Dockerfile, bin/releng/locales.sh, bin/releng/tools.sh, package.json
Keep it modern.
This is to also fix an dependency error:
```
#14 3.742 warning file-loader@2.0.0: Invalid bin field for "file-loader".
#14 21.11 info fsevents@1.2.13: The platform "linux" is incompatible with this module.
#14 21.11 info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
#14 21.12 info fsevents@2.3.2: The platform "linux" is incompatible with this module.
#14 21.12 info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
#14 21.13 error d3@7.6.1: The engine "node" is incompatible with this module. Expected version ">=12". Got "10.19.0"
#14 21.14 error Found incompatible module.
```
- https://github.com/eventum/eventum/pull/1307
=> Use node 16 for release image

.github/workflows/release.yml, .github/workflows/tests.yml
- https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
- https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
=> Update GitHub actions deprecations

CHANGELOG.md, src/ServiceContainer.php
Fixes #1435, #1174
Ensure the kernel is booted before getting a named logger instance.
=> Fix exception in ManageBaseController

CHANGELOG.md, res/assets/sass/main.scss
Select boxes enriched with jquery-chosen are not properly rendered in Firefox: The dropdown is permanently visible (albeit initially empty), even if the select box is closed.
The issue seems to be caused by custom CSS rules which date back to a time when the plugin worked differently.
=> Fix "chosen" select box rendering in Firefox

CHANGELOG.md, templates/manage/users_list.tpl.html
When filtering the users list to a single entry, Eventum will
incorrectly refuse to deactivate that account because the number of
selected entries equals the number of visible entries.
Adapt the check to compare with the size of the unfiltered list.
=> Fix false error when disabling users in filtered list
