- templates/add_phone_entry.tpl.html
- templates/add_time_tracking.tpl.html
- templates/base.tpl.html
- templates/convert_note.tpl.html
- templates/custom_fields_form.tpl.html
- templates/file_upload.tpl.html
- templates/post_note.tpl.html
- templates/send.tpl.html
- templates/view.tpl.html
- templates/view_note.tpl.html
Also always append APP_TITLE to title
> Restore $extra_title functionality

- lib/eventum/class.mail_helper.php
- tests/Mail_HelperTest.php
Added tests for parsing email addresses.
This is the first time I've added a test case I believe so I wanted you to check it out and let me know if there are any issues.
> Fix error parsing confusing email addresses.

- docs/ChangeLog
- htdocs/new.php
- lib/eventum/class.access.php
- lib/eventum/class.custom_field.php
- lib/eventum/class.issue.php
- lib/eventum/class.workflow.php
- lib/eventum/workflow/class.abstract_workflow_backend.php
- templates/edit_custom_fields.tpl.html
- templates/new_form.tpl.html
- templates/view_form.tpl.html
- upgrade/patches/23_issue_clone.sql
I've moved the logic from new.php into the and cleaned up the changelog. Let me know if you have any more feedback or if I should merge this.
> Clone issue

- htdocs/css/main.css
- htdocs/css/page.css
- htdocs/update.php
- htdocs/view.php
- templates/update_form.tpl.html
- templates/view_form.tpl.html
Changed back to using tables for view and update page layout. Fixes a bunch of annoying UI problems.
There are still some minor glitches but it is better then what we have now.
> Table based layout

- htdocs/css/page.css
* dropzone.js drag and drop dropzone are more visible and nicer (note+email)
* added dashed border and more space
> Dropzone drag'n'drop dropzone area more visible

- htdocs/css/main.css
> use less aggressive hover color (default eventum color)

- htdocs/manage/email_alias.php
- templates/manage/email_alias.tpl.html
- templates/manage/users.tpl.html
User administration small tunings
* trim email input field (and it's validation check)
* changed table td widths to be more nicer, (it also removed total 120% with)
> Adminstration user fixes

- htdocs/css/main.css
> create issue - center footer buttons

- htdocs/edit_reporter.php
- templates/edit_reporter.tpl.html
trim email input field (and it's validation check)
Similar to https://github.com/eventum/eventum/pull/62
> trim email input field (and it's validation check) before submitting Edit Reporter email

- htdocs/js/page.js
- htdocs/manage/anonymous.php
- htdocs/manage/field_display.php
- htdocs/manage/general.php
- htdocs/new.php
- htdocs/setup/index.php
- htdocs/update.php
- htdocs/view.php
- lib/eventum/class.project.php
- templates/manage/anonymous.tpl.html
- templates/manage/field_display.tpl.html
- templates/manage/general.tpl.html
- templates/new_form.tpl.html
- templates/update_form.tpl.html
- templates/view_form.tpl.html
- upgrade/patches/32_project_field_required.sql
The "Fields to Display" manage page now allows you to select which fields should be required.
The "Allow Unassigned issues" setting in admin is now removed.
> Add admin interface for required fields.

- htdocs/css/main.css
- htdocs/css/page.css
- templates/new_form.tpl.html
* Chosen overrides, make it wider
* New issue 100% width
* Custom fields chosen field wider
* Cosmetics
> New form fixes

- bin/release.sh
- composer.json
- htdocs/js/main.js
- templates/base.tpl.html
[Autosize](http://www.jacklmoore.com/autosize/) is a small, stand-alone script to automatically adjust textarea height to fit text.
> Add autosize plugin to all TEXAREAs

- htdocs/reports/custom_fields_weekly.php
- htdocs/reports/weekly.php
support bookmarklets by using REQUEST instead of POST
for custom_fields_weekly.php and weekly.php
> POST -> REQUEST

- htdocs/js/main.js
- templates/select_project.tpl.html
Very small change to use JQuery to submit automatically when using the radio select in project_select.php.  One click instead of two.
There may be a better JQuery selector than what I have used, but it works.
> Tiny change to submit on project selection

- lib/eventum/auth/AuthPassword.php
- lib/eventum/auth/class.mysql_auth_backend.php
the idea was to do this at least one release after new hash introduction. so here it is.
it will also upgrade new hashes if there is more secure algorithm enabled by default.
> upgrade password hash on successful login

- lib/eventum/class.help.php
- lib/eventum/class.issue.php
- lib/eventum/class.link_filter.php
- lib/eventum/class.mime_helper.php
- lib/eventum/class.search_profile.php
- lib/eventum/class.support.php
Minor declaration changes to avoid notifications.
> Fix static notifications in class.issue.php

- htdocs/js/main.js
- htdocs/js/page.js
- lib/eventum/class.custom_field.php
- templates/edit_custom_fields.tpl.html
- templates/manage/custom_fields.tpl.html
- templates/update.tpl.html
- upgrade/patches/41_custom_field_required.sql
As requested by @cpinfold 
Not sure about the management UI. I added an always checked (but disabled) check box for the edit form to be consistent. Not sure if it is confusing or helps.
> Added ability to require custom fields on the edit form.

- htdocs/index.php
- lib/eventum/auth/class.auth_backend_interface.php
- lib/eventum/auth/class.cas_auth_backend.php
- lib/eventum/auth/class.ldap_auth_backend.php
- lib/eventum/auth/class.mysql_auth_backend.php
- lib/eventum/class.auth.php
- lib/eventum/class.setup.php
Pretty simple change but since it impacts the auth system I wanted someone else to look at it. Ready for merge if you approve @glensc
> Allow auth backends to auto redirect to external login screen.

- .gitignore
- htdocs/.htaccess.dist
main purpose is to add caching headers in development mode to static files
> add .htaccess to htdocs

- lib/eventum/class.issue.php
- lib/eventum/class.notification.php
> Exclude sender of email from getting standard "new issue" email.

- composer.json
- templates/base.tpl.html
- templates/include/dropzone.tpl.html
- templates/send.tpl.html
adds feature of uploading file from clipboard to file upload dialog when pressing `paste` shortcut (`Ctrl+V` or similar)
based on good blog:
https://sowingseasons.com/blog/coding/2016/01/add-paste-from-clipboard-to-dropzone-js/30744077
using http://bgrins.github.io/filereader.js/
> upload on paste from clipboard

- cli/Makefile
- cli/box.json.dist
- cli/eventum.php
@glensc I know you said you were going to look into the issues building the CLI but I needed to release a new phar for my team so I committed some quick fixes. 
Not sure if you had something else in mind but I thought I'd push them for reference.
> Fixes to allow CLI to be built without errors

- lib/eventum/class.access.php
- lib/eventum/class.group.php
- lib/eventum/class.mail_helper.php
- lib/eventum/class.report.php
- lib/eventum/class.search.php
- lib/eventum/class.user.php
- src/Controller/Helper/AssignHelper.php
- src/Controller/Manage/GroupsController.php
- src/Controller/Manage/UsersController.php
- templates/manage/users.tpl.html
- templates/reports/weekly_data.tpl.html
- upgrade/patches/45_multiple_groups.php
This change allows users to be in more then one group at the same time.
> Allow users to be in multiple groups

- bin/release.sh
- composer.json
- src/Controller/PostNoteController.php
- templates/add_phone_entry.tpl.html
- templates/add_time_tracking.tpl.html
- templates/base.tpl.html
- templates/post_note.tpl.html
- templates/send.tpl.html
Decided to try this approach as it was simple to implement vs using ajax to save client side.
I don't see the need for a user preference on this unless someone else does?
> Autosave notes/emails to local storage in case of browser crash

- lib/eventum/class.issue.php
- lib/eventum/class.project.php
- src/Controller/NewController.php
- templates/fields/access_level.tpl.html
- templates/new_form.tpl.html
> Allow access level to be set when creating an issue.

- htdocs/js/main.js
- src/Controller/PostNoteController.php
- src/Controller/SendController.php
- templates/post_note.tpl.html
- templates/send.tpl.html
#145 enchancement:
This prevents network / server errors from causing saved data to be lost.
Should be good to merge, but wanted others to test it first
> Don't clear saved data until after the next page actually loads,

- bin/release.sh
- composer.json
- lib/eventum/class.mail_queue.php
- lib/eventum/class.workflow.php
This is initial integration point to use Zend\Mail to handle mails. This one uses to fill mail queue.
besides other things, this ensures mails in mail queue table will have `Message-ID` header always present
> use Zend\Mail in addMail

- lib/eventum/class.routing.php
- tests/MailMessageTest.php
> strip out mbox From  header

- htdocs/js/page.js
- lib/eventum/class.issue.php
- lib/eventum/class.note.php
- templates/bulk_update.tpl.html
> Fix error with bulk update not working. 

- src/Controller/Helper/MessagesHelper.php
- src/Session.php
- templates/app_messages.tpl.html
now that #168 is merged, use Symfony FlashBag for flash messages
> use Symfony FlashBag for flash messages

- htdocs/js/page.js
- lib/eventum/class.time_tracking.php
- src/Controller/TimeTrackingController.php
- templates/time_tracking.tpl.html
- templates/time_tracking_entry.tpl.html
- upgrade/patches/58_update_time_tracking.sql
Either the user who submitted them or a manager can edit.
> Allow time tracking entries to be edited

- .gitattributes
- .gitignore
- .travis.yml
- Makefile
- bin/ci/snapshot.sh
- bin/ci/tools.sh
- bin/release.sh
- build.xml
- cli/composer.json
- docs/RELEASE_PROCESS.md
- lib/eventum/class.email_account.php
add travis configuration to make and publish release tarballs automatically on tag push
> add travis configuration to make releases

- ChangeLog.md
- src/Controller/SendController.php
- templates/notes.tpl.html
- templates/send.tpl.html
- templates/view_note.tpl.html
Added the ability to reply to internal notes as emails
> Reply as email

- templates/manage/time_tracking.tpl.html
Nothing Displayed on update one Category in "Existing Categories"  when I "Manage Time Tracking Categories" in "Manage Projects"
> admin/time_tracking: Nothing Displayed on update "Existing Categories"

- ChangeLog.md
- lib/eventum/class.attachment.php
- lib/eventum/class.category.php
- lib/eventum/class.custom_field.php
- lib/eventum/class.email_account.php
- lib/eventum/class.filter.php
- lib/eventum/class.group.php
- lib/eventum/class.history.php
- lib/eventum/class.impact_analysis.php
- lib/eventum/class.issue.php
- lib/eventum/class.note.php
- lib/eventum/class.notification.php
- lib/eventum/class.phone_support.php
- lib/eventum/class.project.php
- lib/eventum/class.release.php
- lib/eventum/class.scm.php
- lib/eventum/class.time_tracking.php
- src/Controller/Manage/ProjectsController.php
- templates/manage/projects.tpl.html
remove such dangerous feature like delete project  that also deletes all issues and relations to the issues.
approved by @balsdorf 
and we discussed, if someone really needs such functionality, a custom script can be made.
> WIP: remove dangerous feature: removing projects and issues by project

- ChangeLog.md
- htdocs/js/page.js
- lib/eventum/class.access.php
- templates/checkins.tpl.html
- templates/checkins_list.tpl.html
- templates/view.tpl.html
> fix SCM checkins being displayed as "public", fixes #215

- lib/eventum/class.issue.php
- lib/eventum/class.notification.php
- lib/eventum/report/RecentActivity.php
- src/Controller/Manage/ColumnDisplayController.php
- src/Controller/Manage/CustomFieldsController.php
- src/Controller/Manage/FieldDisplayController.php
- src/Controller/Report/WorkloadDateRangeController.php
- templates/current_filters.tpl.html
- templates/manage/column_display.tpl.html
- templates/manage/field_display.tpl.html
- templates/manage/general.tpl.html
- templates/manage/products.tpl.html
- templates/reports/category_statuses.tpl.html
- templates/reports/custom_fields.tpl.html
- templates/reports/index.tpl.html
- templates/reports/issue_user.tpl.html
- templates/reports/open_issues.tpl.html
- templates/reports/recent_activity.tpl.html
- templates/reports/reports_base.tpl.html
- templates/reports/stalled_issues.tpl.html
- templates/reports/weekly.tpl.html
- templates/reports/workload_date_range.tpl.html
- templates/reports/workload_time_period.tpl.html
- templates/update_form.tpl.html
Proposal to add some missing translate of strings.
(Sorry, I missed "git diff --check".)
> Add translate

- ChangeLog.md
- lib/eventum/class.search.php
> Allow sort by "% Complete" column

- ChangeLog.md
- docs/examples/workflow/class.example.php
- htdocs/setup/index.php
- lib/eventum/auth/APIAuthToken.php
- lib/eventum/class.access.php
- lib/eventum/class.custom_field.php
- lib/eventum/class.date_helper.php
- lib/eventum/class.db_helper.php
- lib/eventum/class.group.php
- lib/eventum/class.issue.php
- lib/eventum/class.mail_helper.php
- lib/eventum/class.notification.php
- lib/eventum/class.partner.php
- lib/eventum/class.report.php
- lib/eventum/class.search.php
- lib/eventum/class.support.php
- lib/eventum/class.workflow.php
- lib/eventum/crm/class.contract.php
- lib/eventum/irc/AbstractBotCommands.php
- lib/eventum/irc/BotCommands.php
- lib/eventum/irc/Eventum_Bot.php
- lib/eventum/workflow/class.abstract_workflow_backend.php
- src/Crypto/CryptoManager.php
fixes #218 
Found some with static analyze in PHPStorm and some by running manually.
configured php.ini:
```
error_reporting = E_ALL & ~E_DEPRECATED
```
> fix some strict mode issues, fixes #218

- ChangeLog.md
- composer.json
- lib/eventum/class.mail_helper.php
- lib/eventum/class.mail_queue.php
- src/Mail/MailMessage.php
- src/Mail/MailTransport.php
- tests/MailTransportTest.php
multiple recipients likely broken, not tested and not sure which code paths use that except mail_queue getMergedList hack. perhaps it's better to drop that mergedlist support even.
> use Zend Mail Transport for mail delivery

- CHANGELOG.md
- bin/extension.php
- src/Command/ExtensionCommand.php
for now it's just for enabling
> add script to manage extensions from cli

- CHANGELOG.md
- db/migrations/20170920202640_eventum_sup_header_length.php
- src/Db/AbstractMigration.php
> unify lengths of header fields

- CHANGELOG.md
- contrib/ldap_import.php
- db/migrations/20170711204425_eventum_status_change_date.php
- db/migrations/20170908145538_eventum_user_external_id_nullable.php
- docs/examples/extension/Event/UserSubscriber.php
- docs/examples/extension/ExampleExtension.php
- lib/eventum/auth/class.cas_auth_backend.php
- lib/eventum/auth/class.ldap_auth_backend.php
- lib/eventum/class.auth.php
- lib/eventum/class.filter.php
- lib/eventum/class.prefs.php
- lib/eventum/class.user.php
- src/Controller/Manage/UsersController.php
- src/Controller/NewController.php
- src/Event/SystemEvents.php
this would allow workflow project to fill external_id, or similar changes.
> add events for user creation/update

- CHANGELOG.md
- src/RPC/RemoteApi.php
- src/RPC/RemoteApiException.php
- src/RPC/XmlRpcServer.php
RPC: log actions server side, not by client,
also logs user agent, changes to add ident in eventum/rpc and eventum/cli are following.
> RPC: log actions server side, not by client

- CHANGELOG.md
- build.xml
the release tarball for 3.3.0 was faulty. #300
> include league flysystem traits in dist tarball

- CHANGELOG.md
- src/RPC/RemoteApi.php
this prevents uploading attachments to issue that don't exist
> rpc/upload: check that user has access to issue

- globals.php
- lib/eventum/class.template_helper.php
- src/AppInfo.php
- src/Controller/Setup/SetupController.php
- src/Monolog/AppInfoProcessor.php
- templates/app_info.tpl.html
didn't like too much logic in template_helper class about version, so moved it out.
> add AppInfo class

- CHANGELOG.md
- lib/eventum/class.note.php
- src/Attachment/AttachmentManager.php
> Fix error deleting attachments when deleting notes

- CHANGELOG.md
- lib/eventum/class.mail_queue.php
- src/Mail/MailTransport.php
> Fix mail queue SMTP to use only email address

- CHANGELOG.md
- src/Command/ReminderCheckCommand.php
Fix commit 7566b51 (on row [106](https://github.com/eventum/eventum/commit/7566b51e6a892f8629937c88884f7e403ebfe8c9#diff-b2a251411e12442eddd8ef7ac7ef78ebR106)).
> FIX sending same reminder repeatedly in ReminderCheckCommand.php

- CHANGELOG.md
- lib/eventum/auth/class.ldap_auth_backend.php
- lib/eventum/class.help.php
- lib/eventum/class.user.php
- src/Auth/Ldap/UserEntry.php
- src/Controller/Manage/LdapController.php
- templates/help/ldap.tpl.html
- templates/help/main.tpl.html
- templates/manage/ldap.tpl.html
- Make user ID attribute configurable to support integration with Microsoft AD
- Fix exception when auto-creating user accounts
> LDAP improvements

- docs/examples/extension/Event/HistorySubscriber.php
- lib/eventum/class.issue.php
- lib/eventum/class.notification.php
- lib/eventum/class.support.php
- src/Command/MailDownloadCommand.php
rather random changes, when tried to test whether the zend-mail replacement merged to master actually works.
it does solve one problem: notification mails created by eventum caused invalid header exception before 7a4078f3a
> mail download: add logging and debugging options

- CHANGELOG.md
- composer.json
- composer.lock
was hoping it would fix linkrefs not working. but it didn't.
https://github.com/cebe/markdown/issues/157
> Update cebe/markdown to 1.2.1

- CHANGELOG.md
- db/migrations/20180501205449_eventum_irc_notice_indices.php
- htdocs/rpc/xmlrpc.php
- lib/eventum/class.auth.php
- lib/eventum/class.issue.php
- lib/eventum/class.misc.php
- lib/eventum/class.project.php
- lib/eventum/class.user.php
- src/Controller/PopupController.php
- src/RPC/RemoteApi.php
- src/RPC/XmlRpcServer.php
xmlrpc method changes:
- isValidLogin checks for user status as well
- new: getClockedInList - unrestricted
- new: getQuarantinedIssueList - unrestricted
- new: getProjectByName - unrestricted
- new: getPendingMessages - requires ROLE_ADMIN
- new: markEventSent - requires ROLE_ADMIN
> XMLRPC: Add methods to support eventum/irc-bot over xmlrpc

- CHANGELOG.md
- db/migrations/20180430183214_eventum_irc_extension.php
- docs/examples/extension/Event/CommitSubscriber.php
- docs/examples/extension/Event/CryptoSubscriber.php
- docs/examples/extension/Event/HistorySubscriber.php
- docs/examples/extension/Event/IrcSubscriber.php
- docs/examples/extension/Event/UserSubscriber.php
- docs/examples/extension/ExampleExtension.php
- lib/eventum/class.notification.php
- lib/eventum/class.reminder_action.php
- lib/eventum/class.support.php
- lib/eventum/class.workflow.php
- src/Controller/AssociateController.php
- src/Event/IrcLegacySubscriber.php
- src/Event/IrcSubscriber.php
- src/Event/SystemEvents.php
- src/EventDispatcher/EventManager.php
- src/Extension/IrcNotifyExtension.php
Intention is to replace IRC with different implementation, post to Slack for example.
> Decouple IRC logic to events

- lib/eventum/class.issue.php
allows avoid relying on global constants in code
> add issue_url to Issue::getDetails result

- CHANGELOG.md
- build.xml
- composer.json
- composer.lock
- ChangeLog: https://github.com/cakephp/phinx/blob/v0.9.2/CHANGELOG.md
- Phinx docs: 
- http://docs.phinx.org/en/latest/ 
- https://book.cakephp.org/3.0/en/phinx.html
> Update phinx to 0.9.x

- CHANGELOG.md
- lib/eventum/class.history.php
- lib/eventum/class.issue.php
- lib/eventum/class.notification.php
- lib/eventum/class.reminder_action.php
- lib/eventum/class.user.php
- lib/eventum/class.workflow.php
- src/Event/SystemEvents.php
```php
const ISSUE_UPDATED_BEFORE = 'issue.updated.before';
const ISSUE_CREATED = 'issue.created';
const ISSUE_UPDATED = 'issue.updated';
const NOTE_CREATED = 'note.created';
```
> Add events to issue created/updated related events

- CHANGELOG.md
- composer.json
- composer.lock
- htdocs/ajax/update.php
- lib/eventum/class.filter.php
- lib/eventum/class.search.php
- src/Controller/BaseController.php
- src/Controller/Helper/CsrfHelper.php
- src/Controller/Manage/ProjectsController.php
- src/Controller/Manage/UsersController.php
- src/Controller/SwitchController.php
- src/Controller/ValidateController.php
- templates/manage/projects.tpl.html
- templates/manage/users_form.tpl.html
- templates/manage/users_list.tpl.html
- templates/popup.tpl.html
- templates/post_note.tpl.html
* [CVE-2018-12628] Add CSRF protection to user and project admin pages (@balsdorf, Yaroslav Babin)
* [CVE-2018-12621] Fixed open redirect (@balsdorf, Yaroslav Babin)
* [CVE-2018-11569] Fixed remote code execution vulnerability (@balsdorf, Yaroslav Babin)
* [CVE-2018-12622, CVE-2018-12623, CVE-2018-12624, CVE-2018-12625, CVE-2018-12626, CVE-2018-12627] XSS fixes (@balsdorf, Yaroslav Babin)
> Security 2018 05

- composer.lock
- Updating paragonie/random_compat (v2.0.12 => v2.0.15): Loading from cache
- Updating defuse/php-encryption (v2.1.0 => v2.2.0): Loading from cache
- Updating league/flysystem (1.0.44 => 1.0.45): Loading from cache
- Updating smarty/smarty (v3.1.31 => v3.1.32): Loading from cache
- Updating symfony/debug (v3.4.8 => v3.4.12): Loading from cache
- Updating symfony/console (v3.4.8 => v3.4.12): Loading from cache
- Updating symfony/event-dispatcher (v3.4.8 => v3.4.12): Loading from cache
- Updating symfony/polyfill-php70 (v1.7.0 => v1.8.0): Loading from cache
- Updating symfony/http-foundation (v3.4.8 => v3.4.12): Loading from cache
- Updating symfony/options-resolver (v3.4.8 => v3.4.12): Downloading (100%)
- Updating symfony/ldap (v3.4.8 => v3.4.12): Downloading (100%)
- Updating …
> Update composer dependencies for 3.5.2 release

- composer.lock
- Updating paragonie/random_compat (v2.0.15 => v2.0.17)
> update composer deps

- bin/migrate_storage_adapter.php
- src/Console/Command/AttachmentMigrateCommand.php
the command is pretty much supported for undefined future.
it's pretty fine to migrate storage around time-to-time.
> move contrib/migrate_storage_adapter.php to bin

- composer.lock
```
Updating dependencies (including require-dev)
Package operations: 0 installs, 26 updates, 0 removals
- Updating symfony/thanks (v1.0.8 => v1.1.0): Loading from cache
- Updating league/flysystem (1.0.46 => 1.0.49): Loading from cache
- Updating psr/log (1.0.2 => 1.1.0): Loading from cache
- Updating monolog/monolog (1.23.0 => 1.24.0): Loading from cache
- Updating pear/pear-core-minimal (v1.10.3 => v1.10.7): Loading from cache
- Updating smarty-gettext/smarty-gettext (1.5.1 => 1.6.0): Loading from cache
- Updating smarty/smarty (v3.1.32 => v3.1.33): Loading from cache
- Updating symfony/debug (v3.4.14 => v3.4.20): Loading from cache
- Updating symfony/console (v3.4.14 => v3.4.20): Loading from cache
- Updating symfony/event-dispatcher (v3.4.14 => v3.4.20): Loading from cache
- Updating …
```
> update composer vendors

- CHANGELOG.md
- lib/eventum/class.misc.php
- src/Mail/Helper/TextMessage.php
- tests/Mail/TextMessageTest.php
- tests/data/htmltext_emailsource.eml
Fixes #399, cc @TexasGitHubber
> Handle text/html only email rendering

- src/Controller/Helper/CsrfHelper.php
- src/Controller/Manage/UsersController.php
- templates/index.tpl.html
- templates/manage/users_list.tpl.html
Restore unlock user functionality
initially added in 796a62dab but lost with new templates merge.
cc @balsdorf
> manage: restore unlock user functionality

- CHANGELOG.md
- docs/examples/extension/Event/Subscriber/IssuePercentageUpdater.php
- lib/eventum/class.issue.php
- src/TaskList/TaskListItem.php
- src/TaskList/TaskListMatcher.php
- tests/TaskList/TaskListTest.php
- tests/data/tasklist.txt
Refs: #44
MVP to get Issue %-complete updated from issue tasklist.
Example included.
cc @balsdorf
> Add TaskListMatcher with example to update issue complete percentage

- CHANGELOG.md
- src/Scm/Payload/GitlabPayload.php
The `title` attribute was not properly fetched for merge request note event.
refs: #448
> Match better merge request title from GitLab event

- .gitattributes
- CHANGELOG.md
- tests/Mail/TextMessageTest.php
- tests/data/message-chopped.eml
- tests/data/message-chopped.txt
> Add test for #478

- db/migrations/20190228220154_eventum_sides_preference.php
- src/Controller/BaseController.php
- src/Controller/Helper/RepositoryHelper.php
- src/Controller/ViewController.php
- src/Db/Doctrine.php
- src/Model/Entity/UserPreference.php
- src/Model/Repository/UserPreferenceRepository.php
A partial solution for #262 
There's no UI to configure the setting.
> Make issue navigation respect user preference

- CHANGELOG.md
- db/migrations/20190228224331_eventum_preference_boolean.php
- src/Db/Doctrine.php
- src/Model/Entity/UserPreference.php
- src/Model/Repository/UserPreferenceRepository.php
Seems odd to have NULL value for boolean fields; same goes for refresh rate integers.
cc @balsdorf
> Remove NULL values from user_preference table

- CHANGELOG.md
- htdocs/js/page.js
> Increase default height of Issue Reply pop-up

- CHANGELOG.md
- src/Controller/EmailsController.php
- src/Controller/ListController.php
- src/Controller/SendController.php
> initialize usr_id, needed for preferences

- CHANGELOG.md
- init.php
- lib/eventum/class.template_helper.php
- src/Db/Adapter/PdoAdapter.php
- src/Db/Doctrine.php
- src/DebugBarManager.php
- src/Monolog/Logger.php
> Debugbar: Add Doctrine queries Tab

- lib/eventum/class.search.php
- lib/eventum/class.search_profile.php
- lib/eventum/class.user.php
- src/Controller/ListController.php
- src/Db/Doctrine.php
- src/Model/Entity/SearchProfile.php
- src/Model/Repository/SearchProfileRepository.php
- src/Search/Parameters.php
> Search profile refactor

- CHANGELOG.md
- lib/eventum/class.notification.php
Argument 2 passed to [Custom_Field::formatUpdatesToDiffs()](https://github.com/eventum/eventum/blob/v3.6.3/lib/eventum/class.custom_field.php#L113) must be of the type integer or null, string given, called in [lib/eventum/class.notification.php](https://github.com/eventum/eventum/blob/v3.6.3/lib/eventum/class.notification.php#L719) on line 719
> Fix notification role_id type notice

- CHANGELOG.md
- lib/eventum/class.priority.php
- templates/view_form.tpl.html
This got broken in 0c30ba1e via #291: Eventum v3.4.0 (2018-04-22)
cc @balsdorf
> Escape plain description html

- .gitattributes
- composer.json
- composer.lock
- contrib/git/composer-git-merge-driver.gitconfig
setup [composer-git-merge-driver](https://github.com/balbuf/composer-git-merge-driver), should help auto merging composer.lock conflicts.
submitted also upstream: https://github.com/balbuf/composer-git-merge-driver/pull/12
> setup balbuf/composer-git-merge-driver

- CHANGELOG.md
- bin/ci/release.sh
- bin/releng/bump.sh
- build.xml
- composer.json
- composer.lock
- docs/RELEASE_PROCESS.md
- src/AppInfo.php
- src/Version.php
- tests/VersionTest.php
use [ocramius/package-versions] package for version info
[ocramius/package-versions]: https://packagist.org/packages/ocramius/package-versions
could also use:
- https://github.com/Jean85/pretty-package-versions
- https://github.com/nikolaposa/version
> Use ocramius/package-versions for version info

- composer.lock
closes:
- https://github.com/eventum/eventum/pull/557
- https://github.com/eventum/eventum/pull/556
- https://github.com/eventum/eventum/pull/555
- https://github.com/eventum/eventum/pull/554
- https://github.com/eventum/eventum/pull/553
- https://github.com/eventum/eventum/pull/552
- https://github.com/eventum/eventum/pull/551
> composer: update symfony components: v4.2.7 -> v4.2.8

- CHANGELOG.md
- lib/eventum/class.workflow.php
- src/Controller/ViewController.php
- src/Db/Doctrine.php
- src/Model/Entity/Issue.php
- src/Model/Entity/Project.php
- src/Model/Entity/Status.php
- src/Model/Repository/CustomFieldRepository.php
- src/Model/Repository/IssueRepository.php
- src/Model/Repository/ProjectRepository.php
- src/Model/Repository/StatusRepository.php
- src/Model/Repository/UserPreferenceRepository.php
- tests/Db/DoctrineTest.php
- tests/Scm/TestCase.php
This should simplify some of the workflow methods.
> Add Status Entity

- composer.lock
- symfony/browserkit-4.3.0 - replaces https://github.com/eventum/eventum/pull/586
- symfony/eventdispatcher-4.3.0 - replaces https://github.com/eventum/eventum/pull/587
- symfony/filesystem-4.3.0 - replaces https://github.com/eventum/eventum/pull/581
- symfony/httpfoundation-4.3.0 - replaces https://github.com/eventum/eventum/pull/584
- symfony/ldap-4.3.0 - replaces https://github.com/eventum/eventum/pull/582
- symfony/securitycsrf-4.3.0 - replaces https://github.com/eventum/eventum/pull/585
- symfony/vardumper-4.3.0 - replaces https://github.com/eventum/eventum/pull/580
- symfony/varexporter-4.3.0 - replaces https://github.com/eventum/eventum/pull/583
details:
```
Loading composer repositories with package information
Package …
```
> cupdate symfony deps to 4.3.0

- CHANGELOG.md
- config/routes.yml
- src/Controller/ForgotPasswordController.php
> forgot_password: always render response

- composer.lock
```
Loading composer repositories with package information
Package operations: 4 installs, 42 updates, 1 removal
- Removing symfony/contracts (v1.1.1)
- Updating cakephp/collection (3.7.8 => 3.8.0): Loading from cache
- Updating cakephp/core (3.7.8 => 3.8.0): Loading from cache
- Updating cakephp/utility (3.7.8 => 3.8.0): Loading from cache
- Updating cakephp/log (3.7.8 => 3.8.0): Loading from cache
- Updating cakephp/datasource (3.7.8 => 3.8.0): Loading from cache
- Updating cakephp/cache (3.7.8 => 3.8.0): Loading from cache
- Updating cakephp/database (3.7.8 => 3.8.0): Loading from cache
- Updating doctrine/collections (v1.6.1 => v1.6.2): Loading from cache
- Updating doctrine/lexer (v1.0.1 => 1.0.2): Loading from cache
- …
```
> update all composer dependencies

- composer.json
- composer.lock
Typical update dependencies before making a release.
```
Package operations: 0 installs, 44 updates, 0 removals
- Updating cakephp/collection (3.8.0 => 3.8.1): Loading from cache
- Updating cakephp/core (3.8.0 => 3.8.1): Loading from cache
- Updating cakephp/utility (3.8.0 => 3.8.1): Loading from cache
- Updating cakephp/log (3.8.0 => 3.8.1): Loading from cache
- Updating cakephp/datasource (3.8.0 => 3.8.1): Loading from cache
- Updating cakephp/cache (3.8.0 => 3.8.1): Loading from cache
- Updating cakephp/database (3.8.0 => 3.8.1): Loading from cache
- Updating phpxmlrpc/phpxmlrpc (4.3.2 => 4.4.1): Loading from cache
- Updating seld/signal-handler (1.1.0 => 1.2.0): Loading from cache
- Updating symfony/console (v4.3.2 => …
```
> update composer dependencies

- CHANGELOG.md
- config/packages/security.yml
- htdocs/setup/index.php
- lib/eventum/class.db_helper.php
- lib/eventum/class.setup.php
- src/Controller/Setup/SetupController.php
- src/Db/Doctrine.php
- src/Kernel.php
Installer got broken with #550.
> Fix installer

- CHANGELOG.md
- lib/eventum/class.auth.php
- lib/eventum/class.issue.php
- lib/eventum/class.note.php
- src/Controller/CloseController.php
Broken in #161: https://github.com/eventum/eventum/pull/161#issuecomment-517734831
> Restore close notification emails

- CHANGELOG.md
- init.php
- src/EventDispatcher/EventManager.php
https://symfony.com/blog/new-in-symfony-4-3-simpler-event-dispatching
> Update for new EventDispatcherInterface::dispatch() signature

- CHANGELOG.md
- src/Extension/ExtensionManager.php
- src/Extension/Provider/RouteProvider.php
- src/Kernel.php
refs:
- https://github.com/eventum/eventum/issues/652
> Add support for Extensions to add Symfony routes

- CHANGELOG.md
- lib/eventum/class.support.php
- src/Console/Command/MailDownloadCommand.php
- src/Mail/MailMessage.php
```
Uncaught Exception Error: 
"Call to a member function getEmail() on null" at src/Mail/MailMessage.php line 372
[stacktrace]
#0 lib/eventum/class.support.php(517): Eventum\\Mail\\MailMessage->getSender()
#1 src/Console/Command/MailDownloadCommand.php(102): Support::processMailMessage(Object(Eventum\\Mail\\ImapMessage), Array)
#2 src/Console/Command/MailDownloadCommand.php(56): Eventum\\Console\\Command\\MailDownloadCommand->processEmails('7')
#3 vendor/malkusch/lock/classes/mutex/LockMutex.php(42): Eventum\\Console\\Command\\MailDownloadCommand->Eventum\\Console\\Command\\{closure}()
#4 src/ConcurrentLock.php(37): malkusch\\lock\\mutex\\LockMutex->synchronized(Object(Closure))
#5 src/Console/Command/MailDownloadCommand.php(57): Eventum\\ConcurrentLock->synchronized(Object(Closure))
#6 …
```
> Catch Uncaught exception on IMAP download errors

- CHANGELOG.md
- docs/examples/extension/CustomField/CscNumberCustomField.php
- docs/examples/extension/CustomField/DefaultValueCustomField.php
- docs/examples/extension/CustomField/DynamicAjaxCustomField.php
- docs/examples/extension/CustomField/DynamicCustomField.php
- docs/examples/extension/CustomField/IsbnHcCustomField.php
- docs/examples/extension/ExampleExtension.php
- docs/examples/extension/Subscriber/CommitSubscriber.php
- docs/examples/extension/Subscriber/CryptoSubscriber.php
- docs/examples/extension/Subscriber/GitlabLinkSubscriber.php
- docs/examples/extension/Subscriber/HistorySubscriber.php
- docs/examples/extension/Subscriber/IrcSubscriber.php
- docs/examples/extension/Subscriber/IssuePercentageUpdater.php
- docs/examples/extension/Subscriber/ShouldEmailAddressSubscriber.php
- docs/examples/extension/Subscriber/UserSubscriber.php
Add example for https://github.com/eventum/eventum/issues/359
> Add example Gitlab remote links Subscriber

- templates/access.tpl.html
- templates/authorized_replier.tpl.html
- templates/bulk_update.tpl.html
- templates/include/new_form.tpl.html
- templates/manage/users_list.tpl.html
- templates/notification.tpl.html
- templates/post_note.tpl.html
- templates/update_form.tpl.html
[source](https://hosted.weblate.org/projects/eventum/translations/source/review/?type=check%3Aellipsis)
> typo ellipsis, added

- templates/removed_emails.tpl.html
Fixes issue  #676 "permanently remove" deleted emails not works
Repair of conflict between body and form ids
> Fix permanently remove deleted emails admin action

- CHANGELOG.md
- htdocs/css/main.css
refs:
- https://github.com/thephpleague/commonmark/issues/381
> Set max-width to inline markdown images

- CHANGELOG.md
- db/migrations/20190924193456_eventum_custom_field_title_size.php
- lib/eventum/class.custom_field.php
- src/Controller/Manage/CustomFieldsController.php
- src/Model/Entity/CustomField.php
- src/Model/Entity/ProjectCustomField.php
- src/Model/Repository/CustomFieldRepository.php
- templates/manage/custom_fields.tpl.html
- tests/CustomField/CustomFieldTest.php
Fixes #682
Also increases size of title and description columns, 32 and 64 seemed too short, for even my testing here :)
> Fix saving custom field attached to multiple projects

- CHANGELOG.md
- src/Mail/MailTransport.php
> SMTP: Allow TLS/SSL even if authentication is not enabled

- CHANGELOG.md
- src/Mail/MailMessage.php
- tests/Mail/HeadersTest.php
This allows set custom message-id if there's a need, for example #415
> MailMessage: add setMessageId method

- CHANGELOG.md
- bin/releng/changelog.sh
- lib/eventum/class.db_helper.php
- src/Controller/Setup/SetupController.php
- src/Setup/DatabaseSetup.php
> Fix DatabaseSetup when using separate user

- CHANGELOG.md
- lib/eventum/class.custom_field.php
- lib/eventum/class.link_filter.php
- lib/eventum/class.misc.php
- lib/eventum/class.project.php
- lib/eventum/class.report.php
- lib/eventum/class.routing.php
- lib/eventum/class.time_tracking.php
- lib/eventum/class.user.php
- src/Model/Entity/CustomField.php
- src/Model/Entity/CustomFieldOption.php
- src/Model/Repository/CustomFieldRepository.php
- tests/CustomField/CustomFieldTest.php
Fixes https://github.com/eventum/eventum/issues/702
Breakage came from 6d309632e3 (v3.6.2-41-g6d309632e), released as 3.6.3
> Fix Custom Field Options order not being respected

- CHANGELOG.md
- config/sphinx.conf.php
- db/migrations/20191021192850_eventum_convert_sphinx_const.php
- src/Config/SphinxConfig.php
This must be released before https://github.com/eventum/eventum/pull/704 can be merged.
> Migrate SPHINX_ constants to setup.php

- CHANGELOG.md
- src/Controller/Manage/ManageBaseController.php
Fixes fatal error in manage interface: https://github.com/eventum/eventum/issues/764
> Catch LdapException in Manage interface

- CHANGELOG.md
- src/Auth/Ldap/LdapConnection.php
- src/Controller/Manage/LdapController.php
- templates/help/ldap.tpl.html
- templates/manage/ldap.tpl.html
Supported options are: No encryption, LDAP over SSL and LDAP with
StartTLS.
> LDAP: Support encryption

- lib/eventum/class.template_helper.php
- src/Templating/Asset.php
- tests/AssetTest.php
- tests/data/mix-manifest.json
> Add asset tests

- composer.json
This hints developers how to build assets.
They should ideally get that information from CONTRIBUTING.md
> Suggest composer assets for development

- CHANGELOG.md
- res/logger.php
- var/log/README
One more place found for constant.
Refs: #629, #642
> Remove APP_LOG_PATH constant leftover

- CHANGELOG.md
- composer.json
- composer.lock
- package.json
- webpack.mix.js
- yarn.lock
Hopefully resolves broken dropdown ui:
cc @slay123
> Update jquery chosen from 1.2.0 to 1.8.7

- CHANGELOG.md
- docs/examples/extension/ExampleExtension.php
- docs/examples/extension/Subscriber/PhinxConfig.php
Add example subscriber for event emitted from #516
> Add example Subscriber/PhinxConfig how to add custom migrations

- CHANGELOG.md
- composer.json
- composer.lock
- src/Extension/XhguiProfilerExtension.php
Enable CPU and MEMORY profiling by default.
> Update perftools/php-profiler to 0.3.0

- src/Console/Command/MailDownloadCommand.php
- src/Controller/Helper/LoggerHelper.php
- src/Controller/ScmPingController.php
- src/DebugBarManager.php
- src/Extension/ExtensionManager.php
- src/Logger/LoggerTrait.php
- src/Mail/MailTransport.php
- src/Model/Entity/CustomField.php
- src/Scm/ScmRepository.php
This reduces boilerplate code for logging and makes logging setup lazy initialized.
> Use LoggerTrait in more places

- CHANGELOG.md
- db/migrations/20191021192850_eventum_convert_sphinx_const.php
- db/migrations/20200505043839_eventum_convert_sphinx_const2.php
- lib/eventum/search/class.sphinx_fulltext_search.php
- src/Config/SphinxConfig.php
More constants migration addition to https://github.com/eventum/eventum/pull/705
> Migrate SPHINX_SEARCHD_HOST constant to setup.php

- config/sphinx.conf.php
- lib/eventum/class.search.php
- lib/eventum/search/class.abstract_fulltext_search.php
- lib/eventum/search/class.mysql_fulltext_search.php
- lib/eventum/search/class.sphinx_fulltext_search.php
- src/Config/SphinxConfig.php
- src/ServiceContainer.php
- src/ServiceProvider/FulltextSearchService.php
- src/ServiceProvider/ServiceProvider.php
- templates/quick_filter_form.tpl.html
Dependencies are injected with constructor injection.
> Setup FulltextSearch adapters using service

- .gitignore
- htdocs/js/main.js
- package.json
- res/assets/scripts/ExpandableCell.js
- res/assets/scripts/bootstrap.js
- templates/base.tpl.html
- webpack.mix.js
- yarn.lock
Load ExpandableCell via webpack. This serves as an example how to define javascript modules.
> Extract ExpandableCell into a class

- CHANGELOG.md
- composer.json
- composer.lock
- package.json
- webpack.mix.js
- yarn.lock
npm package can't be found so using GitHub URL:
- https://github.com/widernet/cmd-ctrl-enter/issues/3
> Use cmd-ctrl-enter from node package

- .gitignore
- CHANGELOG.md
- composer.json
- composer.lock
- package.json
- templates/manage/users_list.tpl.html
- webpack.mix.js
- yarn.lock
This also updates from 1.10.4 to 1.10.18
> Use jquery datatables from webpack bundle

- src/Console/Command/MailDownloadCommand.php
- src/Mail/Imap/ImapResource.php
- src/Mail/MailMessage.php
- src/Mail/ProcessMailMessage.php
This way can skip downloading email content knowing it will be skipped
from processing.
> MailDownloader: Process ImapResource first

- .gitignore
- CHANGELOG.md
- bin/releng/build-release.sh
- build.xml
- composer.json
- composer.lock
All components have been moduled to node modules:
- #836
- #842
- #843
- #823
- #835
- #837
> Cleanup leftovers from components

- CHANGELOG.md
- lib/eventum/class.note.php
- src/RPC/RemoteApi.php
Required by https://github.com/eventum/slack-unfurl-eventum/pull/2
> RemoteApi: Add method to retrieve note details by note id

- CHANGELOG.md
- db/migrations/20200523075149_eventum_email_account_types_unify.php
- lib/eventum/class.email_account.php
- src/Console/Command/MailDownloadCommand.php
- src/Controller/Manage/EmailAccountsController.php
- src/Controller/Manage/IssueAutoCreationController.php
- src/Controller/Manage/ProjectsController.php
- src/Db/Doctrine.php
- src/Event/Subscriber/CryptoSubscriber.php
- src/Model/Entity/EmailAccount.php
- src/Model/Repository/EmailAccountRepository.php
- src/Model/Repository/Traits/FindByIdTrait.php
- templates/manage/email_accounts.tpl.html
This is code cleanup that makes use of current usage patterns.
> Migrate Email_Account class logic to Models and Doctrine Repository

- CHANGELOG.md
- db/migrations/20200613040348_eventum_register_partner_legacy_extension.php
- docs/examples/extension/ExampleExtension.php
- docs/examples/extension/Partner/ExamplePartner.php
- lib/eventum/class.partner.php
- lib/eventum/class.support.php
- lib/eventum/class.workflow.php
- lib/eventum/partner/class.abstract_partner_backend.php
- src/Controller/Manage/PartnersController.php
- src/Db/Doctrine.php
- src/Extension/Legacy/PartnerLegacyExtension.php
- src/Model/Entity/PartnerProject.php
- src/Model/Repository/PartnerProjectRepository.php
- src/Model/Repository/ProjectRepository.php
This allows installations that don't need this disable the code paths.
> Move Partner handling out of Workflow class to PartnerLegacyExtension

- lib/eventum/class.history.php
- src/Db/Doctrine.php
- src/Model/Entity/HistoryType.php
- src/Model/Entity/IssueHistory.php
- src/Model/Repository/IssueHistoryRepository.php
- tests/Db/HistoryTest.php
- tests/Traits/DoctrineTrait.php
Finish some old changeset from 2017
> Implement getIssueCloser in Doctrine

- CHANGELOG.md
- build.xml
- composer.json
- composer.lock
- docs/examples/extension/Subscriber/CryptoSubscriber.php
- lib/eventum/class.auth.php
- lib/eventum/workflow/class.abstract_workflow_backend.php
- src/Auth/Adapter/Factory.php
- src/Auth/Ldap/LdapConnection.php
- src/Auth/Ldap/UserEntry.php
- src/Config/Config.php
- src/Controller/Manage/AuthController.php
- src/Controller/Manage/LdapController.php
- src/Crypto/CryptoUpgradeManager.php
- src/Event/ConfigUpdateEvent.php
- src/Extension/ExtensionManager.php
- src/Monolog/Logger.php
- src/Scm/ScmRepository.php
https://github.com/zendframework/zend-config repository was abandoned on 2019-12-31
> Switch to use laminas/laminas-config  instead of zendframework/zend-config

- res/routes.yml
- res/routes_manage.yml
- res/routes_reports.yml
- src/Controller/BaseController.php
- src/Controller/Manage/UsersController.php
- src/Kernel.php
This allows to run the application via router, example via Symfony cli:
```
symfony serve --document-root=htdocs
```
> Define all controllers in Symfony routes

- lib/eventum/class.email_account.php
- src/Controller/Manage/EmailAccountsController.php
- src/Event/Subscriber/CryptoSubscriber.php
- src/Model/Entity/EmailAccount.php
Fixes regression from #850 that encryption can't be enabled without an error.
> Fix getPassword to return EncryptedValue object

- CHANGELOG.md
- res/assets/scripts/Validation.js
- res/assets/scripts/app.js
- res/assets/scripts/pages/AdvSearch.js
- res/assets/scripts/pages/CloseIssue.js
- res/assets/scripts/pages/CustomFieldOptions.js
- res/assets/scripts/pages/IssueUpdate.js
- res/assets/scripts/pages/IssueView.js
- res/assets/scripts/pages/ListIssues.js
- res/assets/scripts/pages/NewIssue.js
- res/assets/scripts/pages/Preferences.js
- res/assets/scripts/pages/Product.js
- res/assets/scripts/pages/Stats.js
This is fixes to either regression introduced from #852 or #861.
> Fix JavaScript this context regression

- CHANGELOG.md
- lib/eventum/class.setup.php
- lib/eventum/class.template_helper.php
- package.json
- src/Controller/Manage/GeneralController.php
- src/Event/ConfigUpdateEvent.php
- src/Event/SystemEvents.php
- src/Extension/SentryExtension.php
- templates/base.tpl.html
- templates/manage/general.tpl.html
- templates/manage/general/sentry.tpl.html
- templates/sentry.tpl.html
- webpack.mix.js
- yarn.lock
> Add support for Sentry JavaScript monitoring

- CHANGELOG.md
- lib/eventum/class.issue.php
- lib/eventum/class.note.php
- lib/eventum/class.notification.php
- res/assets/sass/main.scss
- src/Model/Entity/Issue.php
- src/Model/Entity/User.php
- src/Model/Repository/CommitRepository.php
- src/Model/Repository/UserRepository.php
- templates/notes.tpl.html
- templates/notification.tpl.html
- templates/view_form.tpl.html
Shows user status if it is not "active":
> Show user inactive status

- res/assets/scripts/pages/IssueView.js
Continuation of #884 fixing regressions from  #884 or #852 or even #861.
> Fix event context passing of click handlers

- CHANGELOG.md
- composer.json
- composer.lock
- symfony.lock
Release notes:
- https://github.com/laminas/laminas-mail/releases/tag/2.12.0
> Update laminas/laminas-mail (2.11.0 => 2.12.0)

- bin/console.php
- bin/upgrade.php
- htdocs/setup/index.php
- lib/eventum/class.auth.php
- lib/eventum/class.setup.php
- src/Kernel.php
- src/ServiceContainer.php
- src/ServiceProvider/ServiceProvider.php
- src/Setup/Requirements.php
- tests/AuthCookieTest.php
- Add KernelInterface to Pimple container
- Add ContainerInterface to Pimple container
- Make LoggerInterface service public
- Add Setup::getPrivateKeyPath() method
Extracted from https://github.com/eventum/eventum/pull/898 to able to merge safe changes sooner.
> Add KernelInterface, ContainerInterface to Pimple container

- CHANGELOG.md
- lib/eventum/class.project.php
- phinx.php
- res/packages/doctrine.yml
- src/Db/Doctrine.php
- src/DebugBarManager.php
- src/Kernel.php
- src/Model/Repository/CommitRepository.php
- src/Scm/Adapter/Cvs.php
- src/Scm/Adapter/Gitlab.php
- src/Scm/Adapter/Standard.php
- src/ServiceContainer.php
- src/ServiceProvider/ServiceProvider.php
- tests/UserPreferenceTest.php
- tests/bootstrap.php
This simplifies project that only one instance of Doctrine is created.
> Use Doctrine from Symfony in Doctrine::getEntityManager

- bin/console.php
- bin/upgrade.php
- src/Controller/Setup/SetupController.php
- src/Kernel.php
- src/ServiceContainer.php
- src/ServiceProvider/ServiceProvider.php
Due to the recent changes, need to `cache:clear` after making changes to database config.
> Fix install bootstrap

- CHANGELOG.md
- composer.json
- composer.lock
- symfony.lock
Current requirement for Eventum is PHP 7.2
> Replace symfony/polyfill-php72

- composer.json
- composer.lock
- src/Extension/XhguiProfilerExtension.php
requires: 
- https://github.com/perftools/php-profiler/pull/34
> Update perftools/php-profiler to 0.9.0

- CHANGELOG.md
- res/assets/scripts/pages/IssueView.js
> Fix edit time tracking edit popup

- lib/eventum/class.faq.php
- lib/eventum/class.group.php
- lib/eventum/class.priority.php
- lib/eventum/class.reminder_action.php
- lib/eventum/smarty/function.calendar.php
- lib/eventum/smarty/function.get_display_label.php
- lib/eventum/smarty/function.get_display_style.php
- lib/eventum/smarty/function.get_textarea_size.php
- src/Auth/Adapter/CasAdapter.php
- src/Controller/FileUploadController.php
- src/Controller/TimeTrackingController.php
- src/Mail/Helper/AddressHeader.php
- src/RPC/RemoteApiException.php
- src/Scm/ScmRepository.php
Trivial phpstan fixes with default setup (level 0).
> Apply phpstan fixes

- bin/releng/configure.sh
- composer.json
- composer.lock
- src/Extension/XhguiProfilerExtension.php
- symfony.lock
requires: https://github.com/perftools/php-profiler/pull/29
can now remove hacks surrounding faking mongodb dependency.
> Update Xhgui profiler 0.10

- docs/wiki/System-Admin/Displaying-PHP-errors.md
Fixes https://github.com/eventum/eventum/issues/939
> Update documentation about error logs

- CHANGELOG.md
- lib/eventum/class.workflow.php
Fixes https://github.com/eventum/eventum/issues/949
> Fix NOTIFICATION_NOTIFY_ADDRESS event arguments

- CHANGELOG.md
- bin/releng/snapshot.sh
- docs/Customer_API.md
- docs/help/report_priority.md
- docs/help/report_release.md
- docs/wiki/Basic-User/Creating-Issues.md
- docs/wiki/Basic-User/How-issues-are-handled-in-Eventum.md
- docs/wiki/Basic-User/Listing-Issues.md
- docs/wiki/Basic-User/Reporting-System.md
- docs/wiki/Pending-Contributions.md
- docs/wiki/System-Admin/Adding-a-cron-entry.md
- docs/wiki/System-Admin/Become-Super-Administrator.md
- docs/wiki/System-Admin/Installation-notes-for-NetWare.md
- docs/wiki/System-Admin/System-Admin.md
- lib/eventum/class.crm.php
- lib/eventum/class.issue.php
- lib/eventum/class.mail_queue.php
- lib/eventum/class.notification.php
- lib/eventum/class.support.php
- localization/LINGUAS.php
- localization/eventum.pot
- res/assets/scripts/pages/Preferences.js
- src/Attachment/AttachmentManager.php
- src/Export/Model/Issue.php
- src/Mail/MailTransport.php
- src/Model/Repository/CommitRepository.php
- src/Session.php
- tests/Mail/MailMessageTest.php
https://github.com/vlajos/misspell-fixer
Could also set up GitHub action:
- https://github.com/sobolevn/misspell-fixer-action
> Apply spelling fixes by misspell-fixer

- res/assets/scripts/app.js
The regression was introduced in 682a60091 (#884 v3.9.0).
Fixes https://github.com/eventum/eventum/issues/953
> Restore return value of form.validate submit action

- CHANGELOG.md
- composer.json
- composer.lock
- docs/help/index.md
- docs/help/xhgui.md
- src/Controller/HelpController.php
- src/Extension/XhguiProfilerExtension.php
- src/ServiceProvider/MarkdownServiceProvider.php
- templates/manage/general/xhgui.tpl.html
Use stack saver that uploads and if that fails, saves as file:
- https://github.com/perftools/php-profiler/pull/35
> Update xhgui profiler to 0.14

- CHANGELOG.md
- package.json
- res/assets/scripts/Eventum.js
- res/assets/scripts/ExpandableCell.js
- res/assets/scripts/app.js
- src/Controller/HelpController.php
- src/ServiceProvider/MarkdownServiceProvider.php
- webpack.mix.js
- yarn.lock
usage:
add a code-fence with mermaid syntax:
```mermaid
graph LR
A --- B
B-->C[fa:fa-ban forbidden]
B-->D(fa:fa-spinner);
```
this will render as:
docs:
- https://mermaid-js.github.io/mermaid/#/usage?id=usage
refs:
- https://commonmark.thephpleague.com/1.5/customization/event-dispatcher/
> Add Mermaid diagrams rendering support

- CHANGELOG.md
- composer.lock
- https://github.com/laminas/laminas-mail/pull/108
- https://github.com/laminas/laminas-mail/releases/tag/2.12.5
> Update laminas-mail dependency: Fix Invalid header line for Content-Disposition string

- CHANGELOG.md
- templates/add_phone_entry.tpl.html
- templates/bulk_update.tpl.html
- templates/include/md_textarea.tpl.html
- templates/include/new_form.tpl.html
- templates/manage/email_responses.tpl.html
- templates/manage/faq.tpl.html
- templates/manage/news.tpl.html
- templates/post_note.tpl.html
- templates/update_form.tpl.html
Removes duplication added in https://github.com/eventum/eventum/pull/860
Refs:
- https://github.com/eventum/eventum/pull/860#issuecomment-642548807
> Add md_textarea.tpl.html include to handle markdown enabled text areas

- CHANGELOG.md
- bin/upgrade.php
- htdocs/setup/index.php
- init.php
- lib/eventum/class.auth.php
- lib/eventum/class.setup.php
- phinx.php
- res/services.yml
- src/Controller/Setup/SetupController.php
- src/Event/EventListener/NeedsSetupListener.php
- src/Extension/RegisterExtension.php
- src/Kernel.php
- src/Setup/DatabaseSetup.php
- templates/setup.tpl.html
Fixes https://github.com/eventum/eventum/issues/983, https://github.com/eventum/docker/issues/8
> Fix setup for initial install

- CHANGELOG.md
- lib/eventum/class.db_helper.php
- src/Controller/Helper/DbHelper.php
- src/Db/Adapter/NullAdapter.php
- src/Db/Adapter/PdoAdapter.php
- src/Kernel.php
- src/ServiceProvider/ServiceProvider.php
Clean up some legacy, there's only one adapter: pdo.
> Instantiate PdoAdapter directly without layers of wrappers

- .github/workflows/ci.yml
The results are saved as artifacts, not used otherwise.
> Build release tarball, docker image from GHA

- CHANGELOG.md
- composer.json
- composer.lock
This includes bugfixes for:
- https://github.com/laminas/laminas-mail/pull/140
- https://github.com/laminas/laminas-mail/pull/145
- https://github.com/laminas/laminas-mail/pull/134
- https://github.com/laminas/laminas-mail/pull/128
> Update laminas/laminas-mail (2.12.5 => 2.14.0)

- CHANGELOG.md
- init.php
- res/packages/monolog.yml
- src/Controller/Ajax/AjaxBaseController.php
- src/Controller/Ajax/UpdateController.php
- src/Controller/BaseController.php
- src/Controller/DownloadController.php
- src/Controller/Manage/AuthController.php
- src/Controller/Manage/CustomFieldOptionsController.php
- src/Controller/Manage/ProjectsController.php
- src/Controller/Manage/UsersController.php
- src/Controller/NewController.php
- src/Controller/SignupController.php
- src/Controller/SwitchController.php
- src/Controller/UpdateController.php
- src/Controller/ViewController.php
- src/Monolog/Logger.php
- src/ServiceProvider/ServiceProvider.php
This phases out monolog-cascade, seems it's no longer maintained:
- https://github.com/theorchard/monolog-cascade/pull/95
requires:
todo:
- slack notify
> Use logger from Symfony Framework

- CHANGELOG.md
- bin/check_reminders.php
- bin/download_emails.php
- bin/export-issues.php
- bin/extension.php
- bin/ldapsync.php
- bin/migrate_storage_adapter.php
- bin/monitor.php
- bin/process_all_emails.php
- bin/process_mail_queue.php
- bin/truncate_mail_queue.php
- src/Console/Application.php
This is a step to get rid of `mnapoli/silly` dependency.
> Deprecate bin scripts over excuting via bin/console.php

- db/migrations/20180306202659_eventum_maq_message_id.php
- lib/eventum/class.auth.php
- lib/eventum/class.db_helper.php
- phinx.php
- phpunit.xml
- res/packages/monolog.yml
- src/Auth/Adapter/LdapAdapter.php
- src/Monolog/Logger.php
- src/Monolog/MailHandler.php
- src/ServiceContainer.php
- tests/Mail/MailHandlerTest.php
- tests/bootstrap.php
Use logger via symfony container, drop using own own monolog-cascade based logger.
> Use logger via symfony container

- lib/eventum/class.issue.php
- src/Event/SystemEvents.php
- src/Extension/Legacy/CustomerLegacyExtension.php
Creating PR of some old changeset (30 Jul 2020).
> Add ISSUE_CREATE_PARAMS event when creating new issue

- CHANGELOG.md
- src/Controller/Helper/AssignHelper.php
- src/Controller/Helper/AttachHelper.php
- src/Controller/Helper/HelperTrait.php
- src/Controller/Helper/RepositoryHelper.php
This should had been merged before https://github.com/eventum/eventum/pull/1062
> Update properties for AssignHelper for HelperTrait

- CHANGELOG.md
- src/Controller/AdvSearchController.php
- src/Controller/FileUploadController.php
- src/Controller/Helper/AssignHelper.php
- src/Controller/Helper/AttachHelper.php
- src/Controller/Helper/HelperTrait.php
- src/Controller/Helper/RepositoryHelper.php
- src/Controller/ListController.php
- src/Controller/SendController.php
- src/Controller/ViewController.php
Replace and supplement https://github.com/eventum/eventum/pull/1069 for https://github.com/eventum/eventum/pull/1062
> Remove magic self properties, use function arguments

- CHANGELOG.md
- src/Extension/Legacy/CustomerLegacyExtension.php
Fix subscribers registering introduced from https://github.com/eventum/eventum/pull/1063
> Fix CustomerLegacyExtension getSubscribers/getSubscribedEvents

- src/Controller/Ajax/DynamicCustomFieldOptionsController.php
- src/Controller/Helper/RepositoryHelper.php
- src/Controller/Manage/CustomFieldsController.php
- src/Controller/Manage/EmailAccountsController.php
- src/Controller/Manage/ProjectsController.php
- src/Controller/PreferencesController.php
Fixes https://github.com/eventum/eventum/issues/1065
> Avoid using Doctrine in controllers configure() method

- src/Controller/SendController.php
- templates/send.tpl.html
This skips uncaught 500 error if the invalid address was filled by the user.
> Validate from/to/cc headers before submiting email from web

- tests/Mail/MailBuilderTest.php
- tests/Mail/MailMessageTest.php
refs:
- https://github.com/eventum/eventum/issues/1078
> Move MailBuilder related tests to own TestCase

- CHANGELOG.md
- src/Mail/Helper/MimePart.php
- tests/Mail/MailBuilderTest.php
Fixes https://github.com/eventum/eventum/issues/1078
> Use QuotedPrintable to encode filename

- lib/eventum/class.notification.php
- lib/eventum/class.support.php
- lib/eventum/class.user.php
- src/Mail/MailBuilder.php
- tests/Mail/MailBuilderTest.php
- tests/Mail/WarningMessageTest.php
Add methods to be forward compatible with changes to use [symfony/mime].
[symfony/mime]: https://symfony.com/doc/current/components/mime.html
> Add MailBuilder::set methods

- docs/wiki/Upgrading.md
> Rephrase upgrade path

- docs/wiki/System-Admin/Adding-a-cron-entry.md
- docs/wiki/System-Admin/Doing-a-fresh-install.md
- docs/wiki/System-Admin/Email-integration.md
- docs/wiki/System-Admin/Installation-notes-for-Windows.md
- docs/wiki/System-Admin/setting-up-email-routing-with-1-email-account-for-multiple-projects.md
- docs/wiki/Upgrading.md
Cleanup docs, so https://github.com/eventum/eventum/pull/1218 could be merged
> Docs:  Cleanup mentioning old cli script names

- CHANGELOG.md
- src/ServiceContainer.php
This makes it easier for external extensions to have own config section.
> Feature: Add getExtensionConfig helper for external extensions

- CHANGELOG.md
- src/Markdown/MarkdownRenderer.php
- src/ServiceProvider/MarkdownServiceProvider.php
See:
- https://commonmark.thephpleague.com/2.0/upgrading/consumers/#commonmarkconverter-and-githubflavoredmarkdownconverter-constructors
> Fix: Use MarkdownConverter instead of deprecated CommonMarkConverter

- .gitignore
- Makefile
- phive.xml
Use phive to install tools:
- https://github.com/phar-io/phive
> Feature: Use phive to install tools

- .github/workflows/ci.yml
- bin/releng/Dockerfile
Integrate changes from https://github.com/eventum/eventum/pull/1292
> Refactor: Use docker build stage to build release image

- .github/workflows/ci.yml
> Feature: Build docker image using docker/build-push-action

- .github/workflows/automerge.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
- https://docs.github.com/en/actions/using-workflows/reusing-workflows
> CI: Extract workflow jobs to separate files

- composer.json
- composer.lock
Auto updated in 219af22cf6f35e77c16365f62c597c0d8f7977bc via portphp update:
- https://github.com/eventum/eventum/pull/1360
> Fix: Add conflict on symfony/validator 5.x

- CHANGELOG.md
- templates/manage/priorities.tpl.html
- webpack.mix.js
- Add missing jquery-ui source files to webpack
- Avoid hard-coded image URLs in HTML style attributes
- Adapt customized renderItem() function to jquery-ui 1.12
Fixes #1535
> Fix display of icons in priority dropdown list
